import { createHash } from 'node:crypto';

import { canonicalArtifactJson } from '../frontend/src/lib/analysis/artifact-integrity.ts';

export const HISTORICAL_CASE_PACK_NOW = '2026-08-05T03:00:00.000Z';

const FIRST_CAPTURED_AT = '2026-01-01T00:00:00.000Z';
const SECOND_CAPTURED_AT = '2026-02-01T00:00:00.000Z';
const PACKET_LIMITATIONS = [
  'This local package is browser-importable through its top-level case collection and does not upload or submit evidence.',
  'The reviewed flag records a deliberate CLI choice; it does not prove recipient authorisation, factual correctness, or legal sufficiency.',
  'Importing the package does not restore fields excluded by its audience profile.',
];
const REPORT_LIMITATIONS = {
  risk: 'This report contains normalized browser-local observations from WHOISleuth analyst cases. It is not a live lookup and does not contain raw WHOIS, RDAP, DNS, HTML, or responses collected during website checks. Absence of a signal (e.g. no MX record observed) does not prove nonexistence. It may not have been evaluated. Snapshot fingerprints are deduplication identifiers, not cryptographic evidence hashes. Scan-depth and risk-model gates prevent misleading comparisons; "incomparable" means observations differ materially but one or more fields cannot be compared reliably. Generated locally in the browser. Review the package before sharing it.',
  scoring: 'This report contains normalized browser-local observations from WHOISleuth analyst cases. It is not a live lookup and does not contain raw WHOIS, RDAP, DNS, HTML, or responses collected during website checks. Absence of a signal (e.g. no MX record observed) does not prove nonexistence. It may not have been evaluated. Snapshot fingerprints are deduplication identifiers, not cryptographic evidence hashes. Scan-depth and scoring-model gates prevent misleading comparisons; "incomparable" means observations differ materially but one or more fields cannot be compared reliably. Generated locally in the browser. Review the package before sharing it.',
  portable: 'This report contains normalised browser-local observations from WHOISleuth analyst cases. It is not a live lookup and does not contain raw WHOIS, RDAP, DNS, HTML, or responses collected during website checks. Absence of a signal (e.g. no MX record observed) does not prove nonexistence. It may not have been evaluated. Snapshot fingerprints are deduplication identifiers, not cryptographic evidence hashes. Scan-depth and scoring-model gates prevent misleading comparisons; "incomparable" means observations differ materially but one or more fields cannot be compared reliably. Generated locally in the browser. Review the package before sharing it.',
  profile: 'This report contains normalised browser-local observations from WHOISleuth analyst cases. It is not a live lookup and does not contain raw WHOIS, RDAP, DNS, HTML, or responses collected during website checks. Absence of a signal (e.g. no MX record observed) does not prove nonexistence. It may not have been evaluated. Snapshot fingerprints are deduplication identifiers, not cryptographic evidence hashes. Scan-depth and scoring-model gates prevent misleading comparisons; "incomparable" means observations differ materially but one or more fields cannot be compared reliably. Brand Profile references record an explicit analyst-selected association only; they do not establish ownership, attribution, intent, safety, or maliciousness. Generated locally in the browser. Review the package before sharing it.',
} as const;

type HistoricalAudience = 'internal' | 'public' | 'trusted';

// These digests were captured from the historically reconstructed v1
// projections and are deliberately not regenerated by the test suite. They
// pin the exact legacy canonical bytes so a verifier/canonicalizer change
// cannot make every claimed compatibility fixture self-heal.
const FROZEN_HISTORICAL_DIGESTS: Readonly<Record<string, string>> = Object.freeze({
  '2:1:public': 'sha256:1398a2336deaa3ed07bbedb9e2aa10a9298095ae39b1aebdca584e2c63f81aaa',
  '2:1:trusted': 'sha256:9e467582e40365a469a3eb68751041945b760c16337187edee9fc18f855ba1b4',
  '2:1:internal': 'sha256:686ebe7c3f3adc0fd68a427c89391570f645675846c9433e70f7251346e6458f',
  '3:2:public': 'sha256:2e62be99fa0f1164eefa55e829f18b90ed07cde5642ef5c11330e6618cb20c24',
  '3:2:trusted': 'sha256:86009296471e29ea1a00a67671c90d8793e5948e461a60db40ae6833cc18636f',
  '3:2:internal': 'sha256:bd94830e19747ec6a62a83dded188646e1eab21a0cee415b49c54feacd26798f',
  '4:3:public': 'sha256:1c21be4c218ddd695ca34f77ddb82b19870c5108029a43d16b735f8f3445ef95',
  '4:3:trusted': 'sha256:ed5436d7fd11dd301838247d648e0c1c2d01935d424c5d89c47b5917d09aa39d',
  '4:3:internal': 'sha256:40491f18de988594597cffa22b10bbfd080c90c02ea98249609205ceeec8d998',
  '5:3:public': 'sha256:a9fdff56f688bd8d2098686e18cf0b5e41975207177e8fae4c9dd3725193670f',
  '5:3:trusted': 'sha256:a6a714b2a1966a5aec7676822bcc729160aa0436cd78398b7abc9c6ca6ce286a',
  '5:3:internal': 'sha256:26cdd430aad0b33ce787889e6b33cbf014715b59d18930749d02b99f27310191',
  '6:3:public': 'sha256:fcd49257c1624950a2956292f74a0858fad08a6c46d27371fd38df4ffa06a805',
  '6:3:trusted': 'sha256:27a39148e40445ffc8863beea4ec5b157d0098eb7329c1e1e020df11c7cd21e4',
  '6:3:internal': 'sha256:efce6df079dff3c57e7941b581f0dd122437b7677fd12260624ef62329f1f0e8',
  '7:3:public': 'sha256:1f343f942ea7f4831393651fcd56e664164ad38f78a33c23841d2be93f5e01aa',
  '7:3:trusted': 'sha256:a306c7673c8b0cd7d98a0405a443db7f62158c051f6827862e648b9809ac09ab',
  '7:3:internal': 'sha256:4a3d0ce0990f95c104a495352db3db6c716102f9020d0f460fb5d22082d6ee2b',
  '8:3:public': 'sha256:a075b43f94fe51cedfe3e5666eb82defc3a0940f85acaf67de32f797743f1b18',
  '8:3:trusted': 'sha256:2cc17326cb888aaebc680ac8d96c3b3d91aaf1ab2a735ef6cb304fe666c3fed1',
  '8:3:internal': 'sha256:9cc9a453d0893ae976cf971a0e0877e357638ceb6005d3ecdfe1308b91dc694d',
  '9:4:public': 'sha256:cb82b9c597c8b2f4a8ec098edc41ca58f4a384c29da4c663fd2d9ffd5777ec8a',
  '9:4:trusted': 'sha256:d7be26339e13e70e080084a5ff5d4a9a8153a9aa5ccb54cad645b918be0232b1',
  '9:4:internal': 'sha256:4b7947f1a629da00da79e9521335003894ad2d1c97f1cbafe87659fbdf0d8d37',
  '10:5:public': 'sha256:91b8e06718a4b4a99400b60537502239cb3c33dd785dcceb4529810f13913d2d',
  '10:5:trusted': 'sha256:ec5aa12c0dced782088d2e9f26094005a1284acd5e2c8a8d285765498ff84bd1',
  '10:5:internal': 'sha256:d5421324e0bb6790c80ece3da81ae5485bc8ebbc452c9d29544b7ab715a62e76',
  '10:6:public': 'sha256:eae34bb27543c9794fa52a1fbe7cb1be781a56e17cd053c771d0fbdeec80989c',
  '10:6:trusted': 'sha256:d13169baf4353b5f146b654ab227aeca10851518b62864f4003d7e563a87a341',
  '10:6:internal': 'sha256:8a056a9626321b22f725590d892c2de4acfc6f22d9fc0007801cb43b7f079843',
  '11:7:public': 'sha256:fab62bcf75cb5cbb230e6aa3bfb8cf2b0949059f2865bad7e10c7a4639fc7614',
  '11:7:trusted': 'sha256:bea11e9c23f6c0d072355ed7269e8ba166fa52a2c50ae346de1886c6d5448ffc',
  '11:7:internal': 'sha256:a9fcc14f93e1b9eb184ef4a62d5e9c248a42077ab695eba4a980564bc5d63808',
  '12:8:public': 'sha256:6d8ca5bcf4a1c92f4c3314e7a6989cd1765effd62e99d2206d3cf65099f66d82',
  '12:8:trusted': 'sha256:731aa37614feffb4fb8444596fc7831d96d2cccec1b28ced185987c3aa1f3afe',
  '12:8:internal': 'sha256:eb599762ee85189b595832a09d0d7274eeb45da82a6e729aa0d8f3bcf0ad03ee',
});

function exclusions(audience: HistoricalAudience, caseVersion: number): string[] {
  if (audience === 'internal') return ['Raw upstream payloads and credentials are outside the case schema.'];
  if (audience === 'trusted') return ['Case notes', 'Recipient values', 'Manual trail targets', 'Raw upstream payloads and credentials'];
  return [
    'Case notes',
    ...(caseVersion >= 12 ? ['Brand Profile references'] : []),
    'Actions and recipient values',
    'Analyst assertions',
    ...(caseVersion >= 11 ? ['Investigation branches'] : []),
    'Manual trail targets',
    'Raw upstream payloads and credentials',
  ];
}

function evidenceSnapshot(caseVersion: number, current: boolean): Record<string, unknown> {
  const second = current;
  const fingerprint = caseVersion <= 7
    ? second ? '1uonnn' : 'xul0z4'
    : caseVersion <= 9
      ? second ? '1hn5lkv' : '3fb6ig'
      : caseVersion <= 11
        ? second ? '1vx7lwy' : '17ccf6b'
        : second ? 'z7kk3f' : 'ihg81o';
  return {
    id: `ev-${fingerprint}`,
    fingerprint,
    firstCapturedAt: FIRST_CAPTURED_AT,
    capturedAt: second ? SECOND_CAPTURED_AT : FIRST_CAPTURED_AT,
    source: 'lookup',
    scanDepth: 'deep',
    availability: 'registered',
    confidence: 'high',
    riskModelVersion: 1,
    riskScore: second ? 30 : 20,
    ...(caseVersion >= 10 ? { opportunityModelVersion: 1 } : {}),
    opportunityScore: second ? 55 : 40,
    riskFactors: [{ label: 'Base', points: second ? 30 : 20 }],
    opportunityFactors: [{ label: 'Open', points: second ? 55 : 40 }],
    registrar: second ? 'New Registrar' : 'Old Registrar',
    createdDate: '2020-01-01T12:00:00.000Z',
    expiryDate: '2027-01-01T12:00:00.000Z',
    nameservers: ['ns1.example.test'],
    hasMx: true,
    hasSpf: false,
    hasDmarc: false,
    activityStatus: 'active',
    websiteProbeDetail: 'Website responded',
    pageTitle: 'Example page',
    httpSummaryVersion: null,
    httpEvidenceStatus: null,
    httpFinalOrigin: null,
    httpResponseStatus: null,
    httpTransportSecurity: null,
    httpRedirectCount: null,
    httpCrossOriginRedirect: null,
    httpHttpsDowngrade: null,
    httpContentType: null,
    httpSecurityHeaders: null,
    faviconMatch: false,
    faviconNearMatch: false,
    reusesOfficialAssets: false,
    hasPasswordField: false,
    ...(caseVersion >= 8 ? { hasExternalFormAction: false } : {}),
    phishingLanguageMatch: null,
    ...(caseVersion >= 10 ? {
      privacyProtected: false,
      idnReferenceMatch: false,
      pageBaselineMatch: false,
      hasActiveBrandProfile: false,
    } : {}),
    ...(caseVersion >= 12 ? {
      profileContextState: null,
      profileContextLimitation: null,
    } : {}),
    mutationTypes: ['replacement'],
  };
}

function historicalResponseRecords(caseVersion: number, reportVersion: number) {
  const evidencePin = caseVersion >= 5 ? {
    id: 'pin-1',
    checkpointId: null,
    field: 'registrar',
    category: 'registration',
    label: 'Registrar',
    value: 'Old Registrar',
    source: 'lookup',
    sourceState: 'complete',
    sourceSchema: null,
    observedAt: FIRST_CAPTURED_AT,
    collectionDepth: 'deep',
    completeness: 'complete',
    truncated: false,
    ...(caseVersion >= 7 ? { transitionExpectation: 'preserve' } : {}),
    limitations: [],
    createdAt: FIRST_CAPTURED_AT,
  } : {
    id: 'pin-1',
    label: 'Registrar',
    value: 'Old Registrar',
    source: 'lookup',
    observedAt: FIRST_CAPTURED_AT,
    completeness: 'complete',
    limitations: [],
    createdAt: FIRST_CAPTURED_AT,
  };
  const assertion = {
    id: 'assertion-1',
    kind: 'hypothesis',
    statement: 'The observed change requires review.',
    rationale: null,
    evidencePinIds: ['pin-1'],
    ...(reportVersion >= 6 ? { evidenceRelations: [{ evidencePinId: 'pin-1', stance: 'supports' }] } : {}),
    state: 'open',
    createdAt: FIRST_CAPTURED_AT,
    updatedAt: SECOND_CAPTURED_AT,
    ...(caseVersion >= 7 ? {
      provenance: {
        origin: 'external_import',
        format: 'stix',
        sourceName: 'Reserved fixture feed',
        sourceDigestSha256: 'a'.repeat(64),
        publisher: null,
        externalId: 'indicator--fixture',
        entityType: 'domain',
        entityValue: 'history.example.test',
        observedAt: FIRST_CAPTURED_AT,
        createdAt: FIRST_CAPTURED_AT,
        modifiedAt: SECOND_CAPTURED_AT,
        confidence: 80,
        labels: ['fixture'],
        markings: [],
      },
    } : {}),
  };
  return {
    evidencePins: [evidencePin],
    decisions: [{
      id: 'decision-1',
      summary: 'Continue review',
      rationale: 'The bounded evidence changed.',
      evidencePinIds: ['pin-1'],
      createdAt: SECOND_CAPTURED_AT,
    }],
    actions: [{
      id: 'action-1',
      type: 'internal_review',
      recipient: 'Internal review team',
      contactSource: 'analyst_supplied',
      contactLimitations: [],
      dueAt: null,
      state: 'planned',
      reference: null,
      followUpAt: null,
      outcome: null,
      createdAt: SECOND_CAPTURED_AT,
      updatedAt: SECOND_CAPTURED_AT,
    }],
    assertions: [assertion],
    manualTrail: [{
      id: 'trail-1',
      kind: 'review',
      summary: 'Reviewed the retained evidence.',
      target: 'history.example.test',
      createdAt: SECOND_CAPTURED_AT,
    }],
    sightings: [{
      id: 'sighting-1',
      state: 'analyst_confirmed',
      sourceClass: 'analyst',
      category: 'registration',
      source: 'Analyst review',
      observedAt: SECOND_CAPTURED_AT,
      completeness: 'complete',
      evidencePinId: 'pin-1',
      limitations: [],
      createdAt: SECOND_CAPTURED_AT,
    }],
    branches: [{
      id: 'branch-1',
      name: 'Registration review',
      state: 'active',
      evidencePinIds: ['pin-1'],
      checkpointIds: [],
      assertionIds: ['assertion-1'],
      actionIds: ['action-1'],
      createdAt: SECOND_CAPTURED_AT,
      updatedAt: SECOND_CAPTURED_AT,
    }],
  };
}

function historicalCase(caseVersion: number, audience: HistoricalAudience, reportVersion: number): Record<string, unknown> {
  const response = historicalResponseRecords(caseVersion, reportVersion);
  const publicAudience = audience === 'public';
  const externalAudience = audience !== 'internal';
  return {
    id: 'case-historical',
    domain: 'history.example.test',
    status: 'reviewing',
    disposition: 'unreviewed',
    ...(caseVersion >= 10 ? { reviewReasonCode: null } : {}),
    tags: ['review'],
    notes: [],
    source: 'lookup',
    evidenceHistory: [evidenceSnapshot(caseVersion, false), evidenceSnapshot(caseVersion, true)],
    ...(caseVersion >= 3 ? {
      evidencePins: response.evidencePins,
      decisions: response.decisions,
      actions: publicAudience ? [] : response.actions.map((item) => ({
        ...item,
        recipient: audience === 'trusted' ? '[redacted]' : item.recipient,
      })),
    } : {}),
    ...(caseVersion >= 4 ? {
      assertions: publicAudience ? [] : response.assertions,
      manualTrail: response.manualTrail.map((item) => ({ ...item, target: externalAudience ? null : item.target })),
    } : {}),
    ...(caseVersion >= 9 ? { sightings: response.sightings } : {}),
    ...(caseVersion >= 11 ? { branches: publicAudience ? [] : response.branches } : {}),
    ...(caseVersion >= 12 ? { brandProfileIds: publicAudience ? [] : ['Profile_A'] } : {}),
    createdAt: FIRST_CAPTURED_AT,
    updatedAt: SECOND_CAPTURED_AT,
  };
}

function defaultReportVersion(caseVersion: number): number {
  if (caseVersion === 2) return 1;
  if (caseVersion === 3) return 2;
  if (caseVersion <= 8) return 3;
  if (caseVersion === 9) return 4;
  if (caseVersion === 10) return 6;
  if (caseVersion === 11) return 7;
  return 8;
}

function evidenceChanges() {
  return [
    { field: 'riskScore', label: 'Risk score', before: 20, after: 30, tone: 'warn' },
    { field: 'riskFactors', label: 'Risk factors', before: [{ label: 'Base', points: 20 }], after: [{ label: 'Base', points: 30 }], tone: 'neutral' },
    { field: 'opportunityScore', label: 'Opportunity score', before: 40, after: 55, tone: 'neutral' },
    { field: 'opportunityFactors', label: 'Opportunity factors', before: [{ label: 'Open', points: 40 }], after: [{ label: 'Open', points: 55 }], tone: 'neutral' },
    { field: 'registrar', label: 'Registrar', before: 'Old Registrar', after: 'New Registrar', tone: 'warn' },
  ];
}

function historicalReport(caseVersion: number, reportVersion: number, sourceCase: Record<string, unknown>): Record<string, unknown> {
  const baseline = evidenceSnapshot(caseVersion, false);
  const current = evidenceSnapshot(caseVersion, true);
  return {
    schema: 'whoisleuth.case-report',
    schemaVersion: reportVersion,
    generatedAt: HISTORICAL_CASE_PACK_NOW,
    application: reportVersion >= 6
      ? { name: 'WHOISleuth', version: '1.46.0', projectUrl: 'https://github.com/slicedearth/whoisleuth' }
      : { name: 'WHOISleuth' },
    case: {
      id: 'case-historical',
      domain: 'history.example.test',
      status: 'reviewing',
      disposition: 'unreviewed',
      ...(reportVersion >= 5 ? { reviewReasonCode: null } : {}),
      ...(reportVersion >= 6 ? { interoperabilityTags: [] } : {}),
      ...(reportVersion >= 8 ? { brandProfileIds: structuredClone(sourceCase.brandProfileIds) } : {}),
      tags: ['review'],
      source: 'lookup',
      openedAt: FIRST_CAPTURED_AT,
      updatedAt: SECOND_CAPTURED_AT,
      notesIncluded: false,
    },
    currentAssessment: current,
    evidenceTimeline: [
      {
        snapshot: baseline,
        isBaseline: true,
        hasRepeatedObservation: false,
        changes: null,
        hasIncomparableChange: false,
        incomparableReasons: [],
      },
      {
        snapshot: current,
        isBaseline: false,
        hasRepeatedObservation: true,
        changes: evidenceChanges(),
        hasIncomparableChange: false,
        incomparableReasons: [],
      },
    ],
    ...(reportVersion >= 2 ? {
      analystResponse: {
        evidencePins: structuredClone(sourceCase.evidencePins),
        decisions: structuredClone(sourceCase.decisions),
        actions: structuredClone(sourceCase.actions),
        ...(reportVersion >= 3 ? {
          assertions: structuredClone(sourceCase.assertions),
          manualTrail: structuredClone(sourceCase.manualTrail),
        } : {}),
        ...(reportVersion >= 4 ? { sightings: structuredClone(sourceCase.sightings) } : {}),
        ...(reportVersion >= 7 ? { branches: structuredClone(sourceCase.branches) } : {}),
      },
    } : {}),
    limitations: reportVersion <= 4
      ? REPORT_LIMITATIONS.risk
      : reportVersion === 5
        ? REPORT_LIMITATIONS.scoring
        : reportVersion <= 7
          ? REPORT_LIMITATIONS.portable
          : REPORT_LIMITATIONS.profile,
  };
}

export function resignHistoricalCasePack<T extends Record<string, unknown>>(value: T): T {
  const { integrity: _integrity, ...unsigned } = value;
  return {
    ...unsigned,
    integrity: {
      algorithm: 'SHA-256',
      canonicalization: 'sorted-json-v1',
      digestSha256: `sha256:${createHash('sha256').update(canonicalArtifactJson(unsigned)).digest('hex')}`,
    },
  } as unknown as T;
}

/** Frozen representative projections with independently pinned legacy digests. */
export function historicalCasePackFixture(
  caseVersion: number,
  audience: HistoricalAudience = 'public',
  options: Readonly<{ reportVersion?: number }> = {},
): Record<string, unknown> {
  const reportVersion = options.reportVersion ?? defaultReportVersion(caseVersion);
  const sourceCase = historicalCase(caseVersion, audience, reportVersion);
  const unsigned = {
    version: caseVersion,
    exportedAt: HISTORICAL_CASE_PACK_NOW,
    cases: [sourceCase],
    packet: {
      schema: 'whoisleuth.cli.case-pack',
      version: 1,
      audience,
      reviewed: true,
      reports: [historicalReport(caseVersion, reportVersion, sourceCase)],
      redactionManifest: {
        excluded: exclusions(audience, caseVersion),
        sourceCaseCount: 1,
        ...(caseVersion >= 12 ? {
          brandProfileReferencesOmitted: audience === 'public' ? 1 : 0,
        } : {}),
      },
      limitations: [...PACKET_LIMITATIONS],
    },
  };
  const pack = resignHistoricalCasePack(unsigned);
  const expectedDigest = FROZEN_HISTORICAL_DIGESTS[`${caseVersion}:${reportVersion}:${audience}`];
  const actualDigest = ((((pack as Record<string, unknown>).integrity) as Record<string, unknown>).digestSha256);
  if (!expectedDigest || actualDigest !== expectedDigest) {
    throw new TypeError(`Historical Case-pack fixture ${caseVersion}/${reportVersion}/${audience} no longer matches its frozen digest.`);
  }
  return pack;
}
