<script lang="ts">
  import PageHeading from '$lib/components/PageHeading.svelte';
</script>

<svelte:head><title>Privacy policy · WHOISleuth</title></svelte:head>

<PageHeading eyebrow="Policy" title="Privacy policy" description="How this deployment processes registry data, local investigation state, and session information."><a class="btn back" href="/">← Public overview</a></PageHeading>

<article class="policy card">
  <p><em>Last updated: 17 July 2026</em></p>

  <h2>1. Introduction</h2>
  <p>This policy explains what WHOISleuth processes when you use it, why, and what choices you have. It applies to this deployment. By using the service, you agree to the practices described here.</p>

  <h2>2. Information processed</h2>
  <p><strong>Registry data.</strong> Looking up a domain returns whatever registrant contact data its registry or sponsoring registrar publishes through RDAP or WHOIS. The service relays this already-public registry-ecosystem data at your request; most sources redact it by default.</p>

  <p><strong>Registrar RDAP in deep Lookup.</strong> When a registry RDAP object publishes a complete HTTPS link for the same domain at the sponsoring registrar, a deep non-compact Lookup can relay that one public registrar object as a separately attributed source. It is briefly cached in server memory like other registry responses, displayed in the transient Lookup result, and never consulted by availability or scoring. Fast and compact Bulk requests do not perform the follow-up, and registrar RDAP is not copied into browser-local watchlists, cases, or other compact stores. The deliberate raw unified-response view can contain it; the structured Lookup evidence export retains only its bounded source diagnostics in this version.</p>
  <p><strong>Optional archived-verdict search.</strong> If the operator explicitly enables the URLscan adapter and you select it for a deep single-domain Lookup, the server sends only the canonical registrable domain to URLscan's Search API. It searches existing public scan history and never submits the domain or URL for scanning. The provider also receives ordinary API request metadata and associates the query with the operator's API credential under its own privacy and retention policy. WHOISleuth keeps no provider cache; the bounded normalized response is displayed transiently, excluded from browser-local stores and the structured Lookup evidence export, and never affects availability. Fast and compact Bulk paths never make this request.</p>
  <p><strong>Optional malware-host search.</strong> If the operator explicitly enables the URLhaus adapter and you select it for a deep single-domain Lookup, the server posts only the canonical registrable domain to URLhaus's host API. It searches existing malware-distribution records and never submits a URL, sample, or report. The provider also receives ordinary API request metadata and associates the query with the operator's API credential under its own privacy and retention policy. WHOISleuth keeps no provider cache; the bounded normalized response is displayed transiently, excluded from browser-local stores and the structured Lookup evidence export, and never affects availability. Fast and compact Bulk paths never make this request. Community access is subject to not-for-profit fair-use terms; commercial deployments may require a paid provider agreement.</p>
  <p><strong>Optional malware-IOC search.</strong> If the operator explicitly enables the ThreatFox adapter and you select it for a deep single-domain Lookup, the server sends only the canonical registrable domain in an exact-match search to ThreatFox. It searches retained malware indicators and never submits an IOC, URL, sample, or report. The provider also receives ordinary API request metadata and associates the query with the operator's abuse.ch credential under its own privacy and retention policy. WHOISleuth keeps no provider cache; the bounded normalized response is displayed transiently, excluded from browser-local stores and the structured Lookup evidence export, and never affects availability. Fast and compact Bulk paths never make this request. Older indicators expire from the community API, and commercial deployments may require a paid provider agreement.</p>
  <p><strong>Derived external Risk context.</strong> Optional provider payloads stay transient and separately attributed. A lone publisher, neutral miss, failed provider, unknown provider, or non-phishing/non-malware category adds no Risk points. When positive qualifying records are corroborated across at least two independent publisher families, Risk model v5 can add one bounded factor. Multiple datasets operated by the same publisher count as one source. Browser-local cases and reports can retain the resulting score, model version, and factor label, but not raw provider findings, references, or payloads.</p>
  <p><strong>Technical data.</strong> Standard request metadata, including IP address and timestamps, is processed transiently for login and rate limiting. When the operator enables optional distributed operation limits, the configured counter service stores only operation classes, opaque lease identifiers, expiry timestamps, and a one-way hash of the already-opaque session fingerprint. If durable usage accounting is also enabled, it stores bounded operation-feature identifiers, fixed 24-hour/30-day bucket identifiers, and integer counts. It receives no lookup targets, evidence, responses, browser-local records, or session tokens; leases expire after five minutes and usage counters expire shortly after their fixed window ends.</p>
  <p><strong>Optional hosted scheduled monitoring.</strong> This is disabled by default. When the operator explicitly enables the Netlify worker and a scheduled watchlist is present, it retains the bounded watchlist name, canonical domains, interval, timestamps, compact fast registration evidence, six recent change events, and an opaque resumable run cursor. It never stores raw RDAP or WHOIS payloads, expanded contacts, analyst notes, browser sessions, or deep website content. The complete state is encrypted and authenticated with AES-256-GCM before it is written to the site-wide Netlify Blob store; Netlify stores the ciphertext and ordinary object metadata, while its function runtime necessarily processes the decrypted state transiently to run requested public lookups. The scheduled worker has no public route. A separate authenticated management route lets a signed-in user deliberately schedule a browser-local watchlist, read the bounded hosted projection, pause or resume it, replace its hosted snapshot, restore that compact snapshot into the current browser, or delete the hosted copy. Mutations require a same-origin request and request bodies are capped at 1 MiB. This deployment uses one shared login and has no per-user roles or audit identities, so every person given that login can view and manage the same hosted scheduled-watchlist state. Restoring a snapshot creates or replaces a browser-local watchlist only after explicit confirmation. Disabling the worker stops Blob and lookup work but does not delete existing ciphertext; the operator or an authenticated user must remove hosted state deliberately when its history is no longer required. Replacing or losing the encryption key without migrating the state makes the retained ciphertext unreadable.</p>
  <p><strong>Deep lookup evidence.</strong> A requested deep lookup can display bounded HTTP metadata and static page-identity fields derived from the homepage response already fetched for analysis. Page identity can include language, canonical and meta-refresh targets, selected Open Graph fields, generator metadata, forms, normalized resource counts, external resource and embedded origins, mail-contact domains, download context, recognized public tracking identifiers, and versioned page fingerprints. Fingerprints cover the exact captured body, noise-reduced normalized HTML, visible text, static tag structure, form structure, external resource hosts, and public tracking identifiers. Intermediate normalized markup and visible text are discarded after hashing. URL credentials, queries, fragments, resource and download paths, form-action paths, and complete email addresses are not retained. When the active Brand Profile has a compatible official-site baseline, Lookup compares these bounded components locally and independently. It creates no combined page-similarity score, does not change the Risk score, and does not persist or export the derived comparison. Bulk can also compare bounded nameserver, IP-address, favicon, public-tracking-identifier, and configured official-asset-host observations within its current result set. Monitor can display a capped local table of exact nameserver-set and final-origin relationships derived from the latest compact evidence already held in browser-local cases. These comparisons make no additional requests and are not saved as relationship records. Fingerprints and shared observations support comparison but do not prove authorship, ownership, coordination, intent, or maliciousness. The complete rich page-identity record is not copied into Bulk, watchlists, or analyst cases.</p>
  <p><strong>Audience measurement.</strong> The service does not use advertising, behavioural profiling, or cross-site tracking. Any privacy-preserving audience measurement introduced by the operator must stay on public pages and be described in this policy before it is enabled. Protected investigation routes, lookup terms, saved evidence, and session identifiers remain outside that scope.</p>

  <h2>3. How information is used</h2>
  <ul><li>To perform a lookup, scan, posture audit, or search you request.</li><li>To keep you signed in.</li><li>To enforce limits that protect the service and upstream registries.</li></ul>
  <p>Published registrant data is not used to build profiles, sold, or shared with advertisers.</p>

  <h2>4. Legal basis</h2>
  <p>Where GDPR or similar law applies, operation of requested lookups and anti-abuse controls relies on legitimate interest. Exporting, saving, or acting on displayed data is your decision. Any registrant outreach should remain low-volume, human-reviewed, compliant with applicable law, and stop when requested.</p>

  <h2>5. Third parties</h2>
  <p>Requests may reach the relevant registry or registrar, public DNS, a domain's MTA-STS policy host, <a href="https://crt.sh/" target="_blank" rel="noopener">crt.sh</a>, and the infrastructure hosting this deployment. When the optional archived-verdict adapter is configured and explicitly selected, <a href="https://urlscan.io/privacy/" target="_blank" rel="noopener">URLscan</a> receives the canonical registrable domain and ordinary API request metadata for a search-only request under its own terms, privacy policy, and account quota. When an optional abuse.ch adapter is configured and explicitly selected, <a href="https://abuse.ch/privacy-policy/" target="_blank" rel="noopener">URLhaus or ThreatFox</a> receives the same bounded domain target and ordinary request metadata for a host or exact-match IOC lookup under its own fair-use terms, privacy policy, account quota, and retention rules. These integrations do not submit a target for scanning or reporting. If distributed operation limits are enabled, their configured REST service processes the minimal lease and optional fixed-window counter metadata described above. If hosted scheduled monitoring is enabled, Netlify Functions performs the bounded lookups and Netlify Blobs retains its application-encrypted state and ordinary object metadata. No advertising or CRM processors are used. Any audience-measurement processor would be identified here before it is enabled.</p>

  <h2>6. Cookies and browser storage</h2>
  <p>The service sets one signed session cookie, <code>wrt_session</code>, for up to 30 days. It is HttpOnly, SameSite=Lax, and Secure over HTTPS. It is required for authentication and is not used for tracking.</p>
  <p>Brand profiles, shortlist entries, ordinary watchlists, analyst cases, campaigns, and bounded Certificate Transparency search baselines stay in your browser's local storage. Only a separately selected scheduled watchlist may enter the optional encrypted hosted store described above. Campaigns contain a bounded label, optional description, and normalised case-domain membership only; they do not copy case evidence, notes, status, or disposition. Watchlists and cases may retain compact HTTP facts from deep checks: the final origin without its path or query, response status, transport, redirect count and flags, MIME type, and which selected security headers were present—not their values. CT baselines retain normalised search keywords, observed public domains, timestamps, and result counts so later searches can identify new observations; they can be deleted individually or cleared from Discover. A posture audit sends only the selected official domain and configured DKIM selectors to this deployment. Clearing site data removes all saved browser-local state but does not delete separately retained hosted-monitoring ciphertext.</p>
  <p><strong>Public synthetic demo.</strong> The unauthenticated demo uses fixed fictional fixtures on reserved domains and performs no live analysis request. Progress stays only in the current tab's <code>sessionStorage</code> under <code>whoisleuth:synthetic-demo:v1</code>, never enters production browser-local stores, and is removed by Reset demo or when the tab session ends. Downloaded demo packages are explicitly marked as synthetic and are not live findings or evidence reports.</p>
  <p>CSV and JSON exports are generated in your browser. Campaign exports contain their labels, descriptions, domain membership, and timestamps, so review them before sharing. Evidence exports may contain contact data published in raw RDAP or WHOIS responses and the bounded page-identity evidence displayed by Lookup.</p>

  <h2>7. Retention</h2>
  <p>Lookup and posture results are discarded after each server request. Browser-local investigation data persists until you remove it or clear site data. Optional hosted scheduled-monitoring ciphertext persists until the operator removes its Blob; disabling the worker does not delete it. You are responsible for securing and deleting downloaded exports.</p>

  <h2>8. Security</h2>
  <p>Controls include a shared-password gate, signed HttpOnly cookies, per-IP rate limiting, a restrictive Content Security Policy, and SSRF/DNS-rebinding protections for outbound checks. No system is perfectly secure, and the service is provided as is.</p>

  <h2>9. Your rights</h2>
  <p>Depending on your jurisdiction, you may have rights to access, correct, delete, restrict, or object to processing. The service has no individual user-account database. Requests concerning registry-published data should generally go to the responsible registry or registrar; saved lists and exports remain under your control, and an operator who enables hosted scheduled monitoring must also manage its encrypted Blob state.</p>

  <h2>10. International transfers</h2>
  <p>Registries and hosting infrastructure may operate in other countries, so requested lookups can involve international processing inherent to RDAP, WHOIS, DNS, and web hosting.</p>

  <h2>11. Children's privacy</h2>
  <p>The service is not directed at children and is not knowingly used to collect personal data from children.</p>

  <h2>12. Changes</h2>
  <p>This policy may change over time. Material changes will update the date shown above.</p>

  <h2>13. Contact</h2>
  <p>Public support requests are not handled through this site. People authorised to use the protected console should contact the operator who provided access; data-subject requests should use the contact designated by that operator. The repository contains the complete <a href="https://github.com/slicedearth/whoisleuth/blob/main/PRIVACY.md" target="_blank" rel="noopener">privacy documentation</a>.</p>
</article>

<style>
  .policy{max-width:860px;padding:clamp(22px,4vw,42px)}
  .policy>p:first-child{margin-top:0;color:var(--muted)}
  .policy h2{margin:2rem 0 .65rem;font:700 1.05rem var(--mono);color:var(--accent2)}
  .policy p,.policy li{color:var(--muted);line-height:1.7}
  .policy strong{color:var(--text)}
  .policy a{color:var(--accent);text-decoration:underline;text-underline-offset:3px}
  .policy code{padding:2px 5px;border:1px solid var(--border);border-radius:4px;background:var(--bg);color:var(--text)}
  .policy li+li{margin-top:.35rem}
  .back{align-self:start}
</style>
