<script lang="ts">
  import PageHeading from '$lib/components/PageHeading.svelte';
  import PublicSeo from '$lib/components/PublicSeo.svelte';
  import { WHOISLEUTH_SOURCE_REPOSITORY_URL } from '../../../../../lib/project-metadata.mts';
</script>

<PublicSeo
  title="Privacy policy | WHOISleuth"
  description="How WHOISleuth processes public-source evidence, browser-local investigation state, optional hosted monitoring and local files."
  path="/privacy"
/>

<PageHeading eyebrow="Policy" title="Privacy policy" description="What leaves your device, what stays local, and how retained data can be removed." />

<div class="policy-layout">
  <nav class="policy-index card" aria-label="Privacy policy sections">
    <p class="eyebrow">On this page</p>
    <a href="#privacy-introduction">Introduction</a>
    <a href="#privacy-information">Information processed</a>
    <a href="#privacy-browser">Browser-local data</a>
    <a href="#privacy-network">Network processing</a>
    <a href="#privacy-files">Files and exports</a>
    <a href="#privacy-retention">Retention</a>
    <a href="#privacy-security">Security</a>
    <a href="#privacy-contact">Contact</a>
  </nav>

  <article class="policy card" aria-labelledby="privacy-title">
    <h2 id="privacy-introduction">1. Introduction</h2>
    <p id="privacy-title"><strong>Last updated: 13 September 2026.</strong></p>
    <p>WHOISleuth is local-first. Ordinary investigation state stays in this browser profile, and the service has no general user, Case, or workspace database. Network collection, local retention, export, and active review are separate deliberate actions.</p>
    <p>Only a deliberately started network-capable operation sends its declared bounded target or evidence fields. WHOISleuth does not automatically submit reports, contact recipients, acquire domains, apply defensive controls, or change external infrastructure. Missing, blocked, stale, malformed, partial, unavailable, or unsupported evidence never becomes absence, safety, ownership, control, intent, or remediation.</p>
    <p>This policy describes the public deployment. A self-hosted operator must adapt it when hosting, authentication, enabled providers, retention, or contact routes differ.</p>

    <p>The generated <a href={`${WHOISLEUTH_SOURCE_REPOSITORY_URL}/blob/main/docs/privacy-data-flow-catalogue.md`} target="_blank" rel="noopener">data-flow catalogue<span class="sr-only"> (opens in a new tab)</span></a> lists the exact recipients, retention classes and export boundaries for each capability.</p>

    <h2 id="privacy-information">2. Information processed</h2>
    <p>Depending on the selected operation, WHOISleuth can process a domain, hostname, IP address, ASN, nameserver, certificate-search term, or other explicit technical target; public registry, registrar, WHOIS, DNS, routing, HTTP, TLS, certificate, security.txt, and provider evidence; analyst-supplied workspace records including Case classifications and exact incident links; imported evidence files; authentication and operation-control metadata; and local output selected by the operator.</p>
    <p>Public registration sources can expose contact names, organisations, addresses, email addresses, and telephone numbers. WHOISleuth relays or normalises what the selected source publishes rather than building a separate registrant database. Many sources redact those fields.</p>
    <p>The public synthetic demo uses fixed fictional evidence on reserved domains. It performs no live investigation request and writes no protected workspace data. The deployment has no individual user-account database and no advertising or behavioural audience measurement.</p>

    <h2 id="privacy-browser">3. Browser-local data</h2>
    <p>The default workspace and unencrypted named workspaces store bounded collections in IndexedDB as plaintext JSON. They include Cases, Brand Profiles, watchlists, shortlist entries, campaigns, certificate-search history, custom rules, retained relationships, saved Bulk sessions, website snapshots, investigation templates, Bulk review state and saved List column choices, saved Case views and Analyst Review Item state. Anyone able to use this browser profile may be able to read them.</p>
    <p>Retained files require a separate explicit save. Selected originals are stored unchanged in the current workspace, using its encryption when enabled. Case references include filenames, declared sources and observation times, retention times, byte counts and digests; filesystem paths are not stored. Originals can contain sensitive content that ordinary Case metadata excludes. Public and trusted CLI Case packs exclude these references. JSON backups contain references only, not original bytes. Removing a reference deletes its bytes only when no other Case in the workspace references them. No file is uploaded automatically.</p>
    <p>Tab-scoped dictionaries, candidate handoffs, guide progress and similar transient state use bounded memory or <code>sessionStorage</code>. A one-use candidate handoff uses a random token and is removed when accepted. Appearance preferences (colour, reading density and decorative effects) can use <code>localStorage</code>.</p>
    <p>Named workspaces use separate IndexedDB databases and a local directory of random identifiers, names and timestamps. They share the browser profile and storage quota; names alone do not provide access control. The default workspace keeps existing data unchanged. Each tab selects its workspace in <code>sessionStorage</code>; guide progress, candidate handoffs and named-workspace Brand preferences are scoped to that selection. Appearance stays browser-wide. Backups and imports use the explicitly selected workspace, excluding the directory and tab state. Deleting an inactive named workspace removes its saved collections, not other workspaces or downloaded files. Clearing site data removes all workspaces.</p>
    <p>Image comparison and region editing run in page memory. Explicitly retained edits are separate PNG files with their own digests, source-file fingerprints and region instructions. They keep the source observation time; originals are not overwritten. Unsaved image edits are not recovery drafts. Removing a source can leave its derivative and fingerprint without the original bytes.</p>
    <p>Optional encrypted named workspaces protect saved collection values and record identifiers using AES-256-GCM and keyed collection integrity checks. A passphrase-derived key is held only in the unlocked document, never stored or sent. Reloading, locking or leaving the Console requires another unlock; another tab unlocks independently. Guide progress, candidate handoffs and Brand selection stay in memory in an encrypted workspace, not session storage. Names, collection counts, sizes and timestamps remain visible. Encryption does not protect an unlocked page, a compromised device, weak passphrases, deletion or rollback to an older valid database. There is no passphrase reset. Transfer existing work through a reviewed encrypted backup into a new workspace; the original unencrypted data remains until explicitly deleted.</p>
    <p>Selected Case context uses page memory and the existing local Case store. Selection clears on reload or sign-out and does not initiate collection.</p>
    <p>Individual source refreshes keep minimised facts in page memory, separate from the original Lookup. Selected facts can be retained through Case checkpoint controls or downloaded in a readable comparison. The review retains no raw source payloads or contacts; leaving or reloading Lookup clears its transient history.</p>
    <p>Browser-only filters, searches, timelines, relationship views, posture comparisons, evidence-gap queues, and response preflight derive from retained records without another request. They do not create evidence or silently mark work reviewed.</p>
    <p>Saved Bulk rows and deliberately retained relationships can include bounded contributing-source identities, states and observation times, not raw responses. Older records remain readable with missing provenance marked unknown.</p>
    <p><strong>Compatibility.</strong> Current Case schema 16 can retain the exact normalised submitted hostname and the DNS, TLS and web observation hostname on a new evidence snapshot, analyst decision confidence and its basis, and a response route's observation and review times. Pins and sightings with unknown observation times retain null; saving them does not create a source observation time. Exact public v1 Case schema 12 and published-v2 schemas 13–15 remain readable and migrate directly; migrated fields can remain null, unknown, or blank because WHOISleuth does not reconstruct them from weaker evidence. Case report v12 JSON and Markdown do not add the snapshot hostname. Public CLI case packs clear identifiers, actions, observed-effect reviews, and closure records; ordinary Case, workspace, trusted, and internal files can contain exact investigated hostnames and analyst context.</p>
    <p>Explicitly selected evidence pins can include their own observation hostname in response packets; this remains distinct from the Case's registration domain.</p>
    <p>Saved recheck questions retain an analyst-entered hostname, comparison conditions and optional baseline reference. Answers retain the question context as reviewed. These remain browser-local until exported and are excluded from public Case packs with other analyst assertions and independent review records.</p>
    <p>A Case can retain controlled classifications and exact HTTP(S) incident links as browser-local Case metadata. Exact links can contain public paths, queries, and fragments, so they can be sensitive even when embedded credentials are rejected. They remain local until the analyst opens, exports, or otherwise shares them.</p>
    <p>Separate incident Cases can share a domain while retaining their own IDs, titles and decisions. Analyst-entered titles remain in ordinary Case exports, reports, workspace archives and internal CLI packs; trusted and public CLI packs exclude them. Reusing a selected observation copies only that evidence with its original timestamps, not the source Case's notes or decisions.</p>
    <p>Review copies are ordinary full Case exports, not redacted or encrypted. Returned-file previews stay in page memory. Selected new notes, pins, decisions and assertions are saved locally with their original record times and a handoff entry containing the file digest and selected-record-key digest. Nothing is uploaded; file identity does not authenticate the reviewer. Conflicting entries, response authorisations and unselected records are not imported.</p>
    <p>Brand Profiles can retain official-channel URLs and handles, rights owners, registration identifiers, jurisdictions, source URLs, and review notes. These records can be sensitive and remain browser-local until deliberately exported.</p>
    <p>Saved settings reviews also retain source times, completeness, the profile identifier and a digest of its collection settings, not raw DNS or registry responses.</p>
    <p>Failed reads, quota errors, partial evidence, and unsupported versions remain explicit. They do not become empty collections or evidence of absence. Clearing site data removes the browser workspace, including retained Case hostname history.</p>

    <p><strong>Unfinished Case response forms.</strong> Bounded recovery drafts save automatically in the selected workspace, using its encryption when enabled. They are separate from submitted records and excluded from portable backups, exports and legacy rollback copies. They remain until submitted, discarded, or removed with their Case or workspace. Do not enter credentials into analyst forms. Storage health reads site-wide browser estimates; persistent storage is requested only when selected and is not a backup. Backup preparation is remembered only during the current visit, without confirming that the file was kept or restored.</p>

    <h2 id="privacy-network">4. Hosted and third-party processing</h2>
    <p>Single and Bulk lookups send the selected target and requested mode to this deployment. The server performs only the declared bounded requests and returns a bounded response. Deep Lookup may stream source-state summaries before its final response; these make no additional requests and are not saved as partial evidence. The server does not write ordinary investigation results to a workspace. Selected registration bootstrap and public registration responses can remain briefly in memory to reduce duplicate upstream requests; hosting, edge, and function providers can retain ordinary request or function-log metadata under their own policies.</p>
    <p>By default, for a URL pasted into Lookup, the browser sends only its full hostname for collection, without the port, path, query or fragment. Credential-bearing URLs are rejected. Deliberately retaining an exact Incident URL in a Case is a separate action.</p>
    <p>Explicit <strong>selected URL</strong> collection in Deep Lookup sends the path and query in a request body to the application server, then to the website and its followed redirects. Fragments are not sent. CLI <code>--deep --exact-url</code> makes the same deliberate selection. Retained HTTP provenance omits queries, but paths and page-derived text may contain sensitive information. Compact Case facts and website snapshots retain the selection mode, not the URL path or query; they cannot establish a same-page temporal comparison.</p>
    <p>Registration queries use the registrable domain. Deep DNS, TLS and web probes use the selected hostname; registration-delegation checks retain their own domain. Fast, compact, Bulk and monitoring collection scope is unchanged.</p>
    <p>Deep collection can disclose the target or a related bounded query to the applicable registry or registrar, public DNS resolver, nameserver, HTTP origin, TLS endpoint, certificate-search service, security.txt endpoint, or public-address registration service. Each recipient can observe the source network address and apply its own logging, rate limits, and retention. Deep domain collection can query A, AAAA, CAA, and MX once through one selected public address per nameserver, retaining at most sixteen normalised values for each record type. Direct-authority results stay separately attributed; only authoritative registry evidence decides registration.</p>
    <p>Homepage HTML is processed transiently within the <a href="/request-policy">request-policy limits</a>. Raw HTML is not added to browser-local records or ordinary evidence exports. Capture and analysis limits are disclosed as incomplete evidence, not absence.</p>
    <p><strong>Optional providers.</strong> Search-only URLscan, URLhaus, and ThreatFox adapters are disabled unless configured and explicitly selected. They receive the canonical registrable domain and ordinary request metadata; they do not receive a scan, sample, report, browser workspace, or Case. A miss, failure, or quota response is not evidence of safety. The checked-in SSLBL certificate projection is local; Lookup does not send its target or certificate to SSLBL. Registrar standing is matched locally using only the numeric IANA ID already present in registration evidence. Lookup makes no additional IANA or ICANN request for it.</p>
    <p><strong>Optional monitoring.</strong> Scheduled monitoring is disabled by default. Scheduled runs use Fast compact collection: registration-led RDAP and the bounded authoritative DNS fallback where required, without WHOIS, HTTP, TLS, page, or optional intelligence collection. The Blob store receives only the bounded application-encrypted compact projection and ordinary object metadata, not the browser workspace or a key embedded in the object. The worker runtime receives the encryption key through its deployment environment, so an operator or hosting runtime with environment access can decrypt the state while configured. Deleting a scheduled watchlist rewrites the encrypted logical state; it does not delete the Blob object. Disabling collection also leaves the object in place. Physical object deletion is a separate deployment-operator action through the hosting platform, as documented in the operations guide.</p>
    <p><strong>Operation controls.</strong> Optional distributed limits send only operation class, opaque lease, expiry, one-way opaque-session fingerprint, fixed usage bucket, and count metadata to the configured counter service. They do not include targets, evidence, Cases, notes, browser records, or session tokens.</p>
    <p><strong>Authentication and Contact.</strong> The Console uses one signed <code>HttpOnly</code>, <code>SameSite=Lax</code> cookie. Its lifetime defaults to 7 days and cannot exceed 30 days. The Contact page keeps its subject and message in page memory. It sends only a fixed contact category and short-lived Turnstile token for verification, then prepares a local email draft. WHOISleuth does not send or retain the draft and accepts no attachment.</p>
    <p><strong>Platform reporting links.</strong> Opening an official provider route is deliberate external navigation. WHOISleuth does not prefetch the route or submit Case data. The destination or local mail application receives only what ordinary navigation and the analyst's later form or email entry provides, under that provider's own terms and privacy notice.</p>

    <h2 id="privacy-files">5. CLI, imports, and exports</h2>
    <p>Portable evidence packages process selected JSON, screenshots and opaque files locally. File bytes are unchanged, unredacted and unencrypted by packaging; original filenames and paths are not retained in the manifest. Declared source identities, source times and local packaging events can be included. Unknown source times remain unknown. Package review uploads nothing, executes no file and changes no saved records. A workspace file requires its separate import preview and confirmation. Checksum identity, supported format, signature trust, timestamp assurance and factual accuracy remain separate results. Downloaded packages remain until the operator deletes them.</p>
    <p>Evidence folders use the same manifest and file identities. Folder review reads only the selected files. Direct browser output requires a folder picker grant, creates a new child folder and reads its files back for verification; handles are not saved or used for background access. CLI output requires a new explicit path. Cancelled or failed writes may leave partial private output for deliberate inspection or deletion. Selected Case-file exports are not complete workspace backups and do not include Case metadata or unselected files.</p>
    <p>Explicit inline review shows paged JSON text or locally decoded PNG pixels, without running document scripts, following links or making page requests. Capture attachment checks compare selected bytes with manifest declarations; matching bytes do not authenticate the capture. Review state stays in page memory and clears when closed or when the page is left.</p>
    <p>The CLI runs on the operator's machine. Offline plans, comparisons, verification, reports, and imports make no network request. Networked commands disclose their target and source boundary. Local input is bounded before parsing, existing output is refused unless replacement is explicit, and files are not uploaded to WHOISleuth.</p>
    <p>An optional signer trust file is read only when explicitly selected. It contains public-key fingerprints, labels and review notes, not private keys. Trust reports include only the matching entry and the file digest, without its path or other entries. The file is not uploaded, discovered automatically or changed by verification.</p>
    <p>Workflow-file output uses adjacent private lock files containing a local process ID. They are removed after the run; interruption can leave one for manual recovery.</p>
    <p>Workflow checkpoints retain selected paths, step evidence, content digests and explicit input bindings. Reused evidence stays local without extraction files. Per-step review confirmations are recorded for the current invocation only; retained checkpoints do not authorise a later network or human-review step.</p>
    <p>Optional metadata CSV retains source versions, collection and report times, collection origin and source-health states alongside the selected results.</p>
    <p>Selected Bulk CSV exports include a review manifest with targets, review filters, source states, observation times and compact Brand Profile provenance. Raw responses, contacts, Profile contents and notes are excluded.</p>
    <p>The offline <code>mail-headers</code> command parses only the bounded header block from a selected message or standard input. Its output can retain a header digest, domain-only identity and routing, reported authentication states, and observation counts. It does not retain address local parts, display names, subject, body, attachments, or raw header values, and makes no network request.</p>
    <p>The isolated <code>dnssec-validate</code> and <code>mail-transport</code> commands require a selected literal public resolver, a local trust anchor, and explicit owned-or-authorised acknowledgement. Mail transport also requires active-probe acknowledgement. It handles at most three selected MX hosts, sends <code>EHLO</code>, and uses <code>STARTTLS</code> only when advertised. It sends no message, authenticates no account, and tests no relay, recipient, mailbox, or catch-all behaviour.</p>
    <p>Imports are validated before preview or merge. Omission does not delete destination data, and imported evidence is not treated as freshly collected or true merely because it parsed. The preview shows normalised Case fields and shortening before retention; only selected findings or claims are imported. A local finding-content digest distinguishes reimports from changed evidence. It is not anonymisation or proof of source authenticity. Full Case exports and reports retain it; recipient response packets omit it.</p>
    <p>A selected Case follow-up calendar identifies only the stable Case reference by default. Investigated domains, recipients, Case types, and event details are separate opt-ins. A calendar application or synchronisation provider can retain any field the analyst chooses to include.</p>
    <p>Saved Case views retain names, search text, status, disposition and sort choices within the current workspace. Workspace backups include them; response packets do not. Applying a view filters retained Cases without making network requests.</p>
    <p>The current writer emits workspace archive version 9. Exact versions 5, 6, 7 and 8 remain readable. Versions 5–8 gain an empty saved-views section without removing existing views. Version 5 also gains an empty Analyst Review Item section without inventing decisions. Versions 1 through 4 and future versions fail without empty import, reset, deletion, or rewrite. Release 1.47.4 can export the exact version-5 and Case-schema-12 public baseline before moving to v2.</p>
    <p>Recovery rehearsal restores a reviewed backup into a new browser-local workspace without switching the active one or applying its preferences. An encrypted backup requires an encrypted destination. Selected original files or evidence packages are matched by complete byte length and digest, not filenames. Rehearsal data remains until deliberately deleted, including after leaving the page. Separate file-backup packages are unencrypted even when the JSON backup is encrypted.</p>
    <p>The optional encrypted workspace envelope remains version 1. Encryption happens in browser memory; the passphrase and derived key are not persisted or sent. It protects the downloaded file while locked, not an open Console or an unencrypted working workspace, compromised device, malicious extension, or weak passphrase.</p>
    <p><strong>Sensitive files.</strong> A full saved Lookup can contain targets, bounded source endpoints and timings, raw RDAP publications, WHOIS response bodies, and publicly published contacts. Current Lookup evidence schema 29 excludes raw registration payloads, expanded contacts, credentials, and complete query-bearing URLs; published v2 schemas 27 and 28 and exact v1 schema 26 remain readable, and schema 26 may contain public contact fields. Case, workspace, graph, campaign, response, and defensive files can identify investigated targets or contain analyst material. Review every file before sharing.</p>
    <p>Checksums and signatures can detect content change or prove a mathematical key relationship under their named contract. They do not prove evidence accuracy, authorship, signer identity, recipient authorisation, or safety.</p>
    <p><strong>Authorised local capture.</strong> The optional capture companion, separate from the hosted application and main CLI, executes remote page JavaScript in a disposable network-bounded browser. Each admitted resource operator receives the exact requested URL, including its path and query. Structured output has no dedicated path or query fields, but the page-controlled title can reproduce them. A local fixed-size screenshot necessarily preserves visible rendered content and may include page text or a reflected path or query. Captures are not uploaded to WHOISleuth and persist until the operator deletes them. Selecting a capture manifest for a Case validates it and imports only sanitised metadata and declared digests. A separate optional attachment selection reads and checks screenshot and DOM-digest bytes in page memory without uploading them. That check and the file bytes are not saved by the Case metadata import by default. An explicit retention option saves the manifest and matching original files with the Case in one transaction. Unmatched files are excluded from that action. A portable evidence package can preserve selected files separately.</p>

    <h2 id="privacy-retention">6. Retention and deletion</h2>
    <ul>
      <li><strong>Transient hosted results:</strong> end with the bounded operation or cache lifetime; platform logs follow the operator's hosting configuration.</li>
      <li><strong>Session cookie:</strong> remains until expiry, sign-out, or browser removal; rotating the signing secret invalidates outstanding sessions.</li>
      <li><strong>Browser workspace:</strong> remains until removed through the relevant control or browser site data is cleared.</li>
      <li><strong>Optional monitoring:</strong> deleting a scheduled watchlist rewrites the encrypted logical state. The Blob object remains until the deployment operator deletes that object through the hosting platform.</li>
      <li><strong>Downloaded and CLI files:</strong> remain on the operator's filesystem until the operator deletes them.</li>
      <li><strong>Contact draft:</strong> remains only in page or email-client memory; WHOISleuth does not retain it.</li>
    </ul>
    <p>Deleting browser data does not delete separately downloaded files. Disabling a feature does not delete data already retained by its operator.</p>

    <h2 id="privacy-security">7. Security and limitations</h2>
    <p>Controls include signed sessions, request-rate and operation limits, restrictive browser policies, bounded parsing, public-address validation, redirect revalidation, DNS-rebinding resistance, and pinned-address connections. Browser future versions are preserved without write where promised; portable future versions are rejected before merge.</p>
    <p>Unencrypted workspaces are readable in IndexedDB, hosting providers can retain ordinary logs, public sources can publish inaccurate or personal data, and local files can be copied outside WHOISleuth. Missing, blocked, stale, malformed, partial, unavailable, or unsupported evidence remains explicitly qualified.</p>

    <h2 id="privacy-contact">8. Operators, rights, and contact</h2>
    <p>Operators are responsible for an appropriate lawful basis, authorisation, provider terms, retention, and response process. This policy is not legal advice. Requests concerning source-published registration data may need to go to the responsible registry or registrar. Browser records and local files remain under the user's or operator's control; operators who enable monitoring must also manage its encrypted object.</p>
    <p>The public deployment uses Netlify for hosting and functions and Cloudflare Turnstile for protected Contact verification. Upstash is used only when distributed operation controls are configured. Public registries, registrars, DNS infrastructure, target services, certificate-search services, and selected providers receive only their applicable bounded request and can operate in other countries under their own terms.</p>
    <p>Use the <a href="/contact">protected Contact page</a> for a privacy request, outbound-request concern, or security report. It reveals the relevant project role address only after verification and prepares an email in your own client; it does not send or retain the draft. The repository contains the complete <a href={`${WHOISLEUTH_SOURCE_REPOSITORY_URL}/blob/main/PRIVACY.md`} target="_blank" rel="noopener">privacy notice<span class="sr-only"> (opens in a new tab)</span></a>.</p>
  </article>
</div>

<style>
  .policy-layout{display:grid;grid-template-columns:190px minmax(0,860px);align-items:start;gap:14px}
  .policy-index{position:sticky;top:18px;display:grid;gap:3px;padding:12px}
  .policy-index p{margin:3px 8px 8px}
  .policy-index a{padding:7px 8px;border-radius:var(--radius-sm);color:var(--muted);font:650 var(--text-2xs) var(--mono)}
  .policy-index a:hover,.policy-index a:focus-visible{background:rgb(var(--accent-rgb) / .07);color:var(--accent)}
  .policy{min-width:0;padding:clamp(22px,4vw,42px)}
  .policy>p:first-child{margin-top:0;color:var(--muted)}
  .policy h2{margin:2rem 0 .65rem;font:700 1.05rem var(--mono);color:var(--interface-accent);scroll-margin-top:24px}
  .policy p,.policy li{color:var(--muted);line-height:1.7}
  .policy strong{color:var(--text)}
  .policy a{color:var(--accent);text-decoration:underline;text-underline-offset:3px}
  .policy code{padding:2px 5px;border:1px solid var(--border);border-radius:4px;background:var(--bg);color:var(--text)}
  .policy li+li{margin-top:.35rem}
  @media(max-width:820px){
    .policy-layout{display:block}
    .policy-index{position:relative;top:auto;grid-template-columns:repeat(2,minmax(0,1fr));gap:3px;margin-bottom:12px;overflow:visible}
    .policy-index p{grid-column:1/-1;margin:3px 8px 8px}
    .policy-index a{min-width:0;overflow-wrap:anywhere}
    .policy h2{scroll-margin-top:18px}
  }
</style>
