<script lang="ts">
  let query=$state('');let loading=$state(false);let error=$state('');let result=$state<Record<string,any>|null>(null);
  const rec=(v:any):Record<string,any>=>v&&typeof v==='object'?v:{};
  const show=(v:any):string=>v==null||v===''?'—':Array.isArray(v)?(v.join(', ')||'—'):typeof v==='object'?show(v.name||v.org||v.handle||v.domain):String(v);
  async function submit(e:SubmitEvent){e.preventDefault();if(!query.trim()||loading)return;loading=true;error='';result=null;try{const r=await fetch(`/api/lookup?q=${encodeURIComponent(query.trim())}`);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Lookup failed (${r.status})`);result=b;requestAnimationFrame(()=>document.querySelector('#result')?.scrollIntoView({behavior:'smooth'}));}catch(e){error=e instanceof Error?e.message:'Lookup failed';}finally{loading=false;}}
</script>
<svelte:head><title>Lookup · WHOISleuth</title></svelte:head>
<section class="heading"><div><p class="eyebrow">Investigate</p><h1>Lookup</h1><p>Resolve a domain, IP address, or ASN through the existing unified RDAP and WHOIS API.</p></div></section>
<form class="search card" onsubmit={submit}><label for="query">Domain, IP address, or ASN</label><div><input id="query" bind:value={query} placeholder="example.com, 192.0.2.1, or AS13335" autocomplete="off" spellcheck="false">{#if query}<button type="button" aria-label="Clear query" onclick={()=>query=''}>×</button>{/if}<button class="primary" disabled={loading||!query.trim()}>{loading?'Looking up…':'Run lookup'}</button></div>{#if error}<p class="error">{error}</p>{/if}</form>
{#if result}{@const av=rec(result.availability)}{@const rp=rec(rec(result.rdap).parsed)}{@const wp=rec(rec(result.whois).parsed)}<section id="result"><div class="result-head"><div><p class="eyebrow">Result</p><h2>{show(result.registrableDomain||result.query)}</h2></div><span>{show(av.state)}</span></div><div class="summaries"><article><small>Registration</small><strong>{show(av.state||wp.registrationStatus)}</strong><p>{show(av.confidence)} confidence</p></article><article><small>Registrar</small><strong>{show(av.registrar||rp.registrar||wp.registrar)}</strong><p>Normalized registry view</p></article><article><small>Created</small><strong>{show(av.createdDate||wp.createdDate)}</strong><p>Registry lifecycle date</p></article><article><small>Website</small><strong>{show(av.activityStatus)}</strong><p>{show(av.websiteProbeDetail)}</p></article></div><div class="sources"><details class="card" open><summary>RDAP</summary><dl><dt>Domain</dt><dd>{show(rp.domain)}</dd><dt>Registrar</dt><dd>{show(rp.registrar)}</dd><dt>Status</dt><dd>{show(rp.statuses)}</dd><dt>Nameservers</dt><dd>{show(rp.nameservers)}</dd></dl></details><details class="card" open><summary>WHOIS</summary><dl><dt>Domain</dt><dd>{show(wp.domainName)}</dd><dt>Registrar</dt><dd>{show(wp.registrar)}</dd><dt>Status</dt><dd>{show(wp.statuses)}</dd><dt>Nameservers</dt><dd>{show(wp.nameservers)}</dd></dl></details></div><details class="raw card"><summary>Raw unified response</summary><pre>{JSON.stringify(result,null,2)}</pre></details></section>{/if}
<style>.search{padding:22px}.search>label{display:block;margin-bottom:9px;font-weight:700}.search>div{position:relative;display:grid;grid-template-columns:1fr auto;gap:10px}.search>div>button[type=button]{position:absolute;right:130px;top:7px;width:32px;height:32px;border:0;background:none}.result-head{display:flex;align-items:end;justify-content:space-between;margin:34px 0 18px}.result-head h2{margin:0;font-size:2.4rem}.result-head>span{padding:8px 11px;border:1px solid var(--border);border-radius:999px;color:var(--accent);text-transform:capitalize}.summaries{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.summaries article{padding:17px;border:1px solid var(--border);border-radius:14px;background:#0c1827}.summaries small,.summaries strong{display:block}.summaries strong{margin-top:12px;overflow-wrap:anywhere}.summaries p{color:var(--muted);font-size:.68rem}.sources{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.sources details,.raw{padding:0;overflow:hidden}summary{padding:17px;cursor:pointer;font-weight:700}dl{display:grid;grid-template-columns:90px 1fr;gap:9px;margin:0;padding:0 17px 17px;font-size:.72rem}dd{margin:0;overflow-wrap:anywhere}.raw{margin-top:12px}pre{max-height:500px;overflow:auto;margin:0;padding:18px;border-top:1px solid var(--border);font-size:.68rem}@media(max-width:900px){.summaries{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.search>div,.summaries,.sources{grid-template-columns:1fr}.search>div>button[type=button]{right:7px}.result-head{align-items:start}}</style>
