import { MAX_INVESTIGATION_MANIFEST_ARTIFACTS, MAX_INVESTIGATION_MANIFEST_ARTIFACT_BYTES, MAX_INVESTIGATION_MANIFEST_TOTAL_BYTES } from '../packages/investigation/investigation-manifest.mts';
import { positional, OPTIONAL_FILE_POSITIONAL, constraint, EMPTY_CONSTRAINTS, commandSeed, flag, file } from './command-definition.mts';

export const ASSURANCE_COMMAND_DEFINITIONS = Object.freeze({
  manifest: commandSeed({
    reference: {
      description: `Record an ordered, path-free manifest for up to ${MAX_INVESTIGATION_MANIFEST_ARTIFACTS} local files. Use --package --output evidence.zip for a ZIP, add --passphrase-file to encrypt the ordinary package, or use --folder ./evidence for a new unencrypted folder. Add --bagit to ZIP or folder output for BagIt 1.0 with SHA-512 checksums.`,
      example: 'whoisleuth manifest lookup.json comparison.json --workflow "domain review" --json',
      boundary: 'Ordinary output contains metadata only. ZIP and folder output include unchanged selected bytes and are private until reviewed for sharing. Folders must be new; existing destinations are never replaced and a failed write may leave explicit partial output. BagIt output is unencrypted; its checksums do not authenticate evidence. Filenames ending in .json are parsed as JSON; other files are opaque and never executed. Original paths are omitted. No network request is made.',
    },
    collection: { scope: `Reads 1 to ${MAX_INVESTIGATION_MANIFEST_ARTIFACTS} local files, at most ${MAX_INVESTIGATION_MANIFEST_ARTIFACT_BYTES / 1024 / 1024} MiB each and ${MAX_INVESTIGATION_MANIFEST_TOTAL_BYTES.toLocaleString('en-AU')} bytes combined; retains no source paths.` },
    summary: 'Build an evidence manifest offline',
    options: ['--workflow', '--configuration-digest', '--package', '--bagit', '--passphrase-file', '--folder', '--json', '--quiet', '--no-color'],
    optionOverrides: {
      '--package': flag('Create a portable evidence ZIP containing the selected files.'),
      '--folder': file('Create a new evidence folder containing the selected files.'),
      '--bagit': flag('Create a BagIt 1.0 package with SHA-512 checksums.'),
    },
    positionals: Object.freeze([positional('artefacts', 'file', 1, MAX_INVESTIGATION_MANIFEST_ARTIFACTS)]),
    constraints: Object.freeze([
    constraint({ kind: 'required', options: ['--workflow'] }),
    constraint({ kind: 'requires_any', option: '--bagit', requiredOptions: ['--package', '--folder'] }),
    constraint({ kind: 'excludes_all', option: '--bagit', excludedOptions: ['--passphrase-file'] }),
    constraint({ kind: 'requires_all', option: '--package', requiredOptions: ['--output'] }),
    constraint({ kind: 'requires_all', option: '--passphrase-file', requiredOptions: ['--package'] }),
    constraint({ kind: 'mutually_exclusive', options: ['--package', '--json'] }),
    constraint({ kind: 'excludes_all', option: '--folder', excludedOptions: ['--package', '--output', '--force'] }),
  ]),
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.investigation-manifest']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "map-observations": commandSeed({
    reference: {
      description: 'Apply one bounded declarative field-mapping profile to local source observations.',
      example: 'whoisleuth map-observations mapping.json --json',
      boundary: 'Profiles select allowlisted dotted fields only. They execute no scripts, make no requests, and emit the browser-compatible external-findings contract.',
    },
    collection: { scope: 'Reads one mapping document capped at 4 MiB and executes no scripts or requests.' },
    summary: 'Apply a declarative observation map offline',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.external-observation-mapping']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "oam-export": commandSeed({
    reference: {
      description: 'Project browser-compatible external findings into a bounded Open Asset Model bridge document.',
      example: 'whoisleuth oam-export external-findings.json --json',
      boundary: 'The projection is offline, preserves source completeness without inventing confidence, and covers only bounded FQDN, IP address, certificate, and related edge vocabulary.',
    },
    collection: { scope: 'Reads one browser-compatible external-findings document and projects bounded graph records locally.' },
    summary: 'Project external findings to Open Asset Model',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.open-asset-model-bridge']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "ct-intake": commandSeed({
    reference: {
      description: 'Normalise source-qualified local certificate events into browser-compatible findings.',
      example: 'whoisleuth ct-intake certificate-events.json --json',
      boundary: 'The command is offline, caps output at 100 findings, and treats every event as a review lead rather than proof of serving or control.',
    },
    collection: { scope: 'Reads one source-qualified event batch capped at 4 MiB and makes no request.' },
    summary: 'Normalise certificate observations offline',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.ct-event-batch', 'whoisleuth.external-findings']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "domain-control": commandSeed({
    reference: {
      description: 'Build an integrity-protected desired-state manifest or compare one with supplied observations.',
      example: 'whoisleuth domain-control domain-control-input.json --json',
      boundary: 'The command is offline and changes no registrar, DNS, mail, or certificate configuration. Only complete, recent source observations can establish drift or expected absence.',
    },
    collection: { scope: 'Reads one bounded desired-state or review document and performs no collection or configuration change.' },
    summary: 'Build or review a domain control manifest',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.domain-control-review-input', 'whoisleuth.cli.domain-control-review']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  assurance: commandSeed({
    reference: {
      description: 'Review a versioned domain change, recovery-dependency, or retirement plan.',
      example: 'whoisleuth assurance domain-assurance.json --json',
      boundary: 'The command is offline and treats every provider label, readiness state, and evidence reference as analyst-authored input. It changes no configuration.',
    },
    collection: { scope: 'Reads one versioned plan capped at 2 MiB and makes no request or configuration change.' },
    summary: 'Review domain change, recovery, or retirement plans',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.domain-assurance.input', 'whoisleuth.domain-assurance']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "change-packet": commandSeed({
    reference: {
      description: 'Assemble pre-change, post-change, and planning evidence into one integrity-protected packet.',
      example: 'whoisleuth change-packet change-review.json --json',
      boundary: 'Assembly is offline. Readiness reflects only the supplied bounded evidence and does not authorise or perform a domain change.',
    },
    collection: { scope: 'Reads one versioned packet input capped at 6 MiB and makes no request or configuration change.' },
    summary: 'Build a reviewed change packet offline',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.domain-change-packet.input', 'whoisleuth.domain-change-packet']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "sharing-review": commandSeed({
    reference: {
      description: 'Lint one reviewed artefact against local integrity, marking, recipient, personal-data, and redaction controls.',
      example: 'whoisleuth sharing-review packet.json --marking amber --recipient-scope organization --purpose "Reviewed incident handoff" --human-reviewed --personal-data-reviewed --redactions-confirmed --json',
      boundary: 'The command is offline and emits only bounded schema/version metadata, no content values, and no raw evidence. Its result is a review aid, not legal advice or recipient authorisation.',
    },
    collection: { scope: 'Reads one bounded artefact, emits only schema/version metadata and no content values, and performs no transmission.' },
    summary: 'Lint an artefact before deliberate sharing',
    options: ['--marking', '--recipient-scope', '--purpose', '--human-reviewed', '--personal-data-reviewed', '--redactions-confirmed', '--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: Object.freeze([
    constraint({ kind: 'required', options: ['--marking', '--recipient-scope', '--purpose'] }),
  ]),
    handlerOwner: 'assurance',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.sharing-review']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
});
