import { LOOKUP_EVIDENCE_SCHEMA_VERSION, V1_PUBLIC_LOOKUP_EVIDENCE_SCHEMA_VERSION } from '../packages/contracts/lookup-evidence.mts';
import { PUBLISHED_V2_LOOKUP_EVIDENCE_VERSIONS, positional, OPTIONAL_FILE_POSITIONAL, constraint, EMPTY_CONSTRAINTS, commandSeed } from './command-definition.mts';

export const HISTORY_COMMAND_DEFINITIONS = Object.freeze({
  diff: commandSeed({
    reference: {
      description: 'Compare an earlier and later artefact from the same retained Lookup, Bulk-session, or domain-portfolio family.',
      example: 'whoisleuth diff earlier.json later.json --json',
      boundary: 'Comparison is offline: the left input is earlier and the right input is later. Inputs must belong to the same supported family. Saved Lookups can describe the same or different domains; same-domain comparisons preserve observation times and collection uncertainty. For a multi-session Bulk export, --left-session selects a session from the left file and --right-session selects one from the right; missing, unavailable, equal, and different evidence remain separate states.',
    },
    collection: { mode: 'offline', scope: 'Reads two compatible retained artefacts capped at 8 MiB each and retains no source paths.' },
    summary: 'Compare two compatible retained artefacts',
    options: ['--left-session', '--right-session', '--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('sources', 'file', 2, 2)]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'history',
    networkEffect: 'offline',
    common: true,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.lookup-diff']),
    primaryArtefacts: Object.freeze(['Retained-evidence comparison']),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  reconcile: commandSeed({
    reference: {
      description: 'Reconcile bounded values across independently labelled observations of one domain.',
      example: 'whoisleuth reconcile office.json mobile.json external.json --json',
      boundary: 'The command is offline, accepts 2 to 5 saved observations for one domain, and never treats labels as proof of network independence or majority agreement as truth.',
    },
    collection: { mode: 'offline', scope: 'Reads 2 to 5 saved observations for one domain, capped at 32 MiB in total.' },
    summary: 'Reconcile independently labelled observations',
    options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('sources', 'file', 2, 5)]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'history',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.lookup-reconciliation']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  timeline: commandSeed({
    reference: {
      description: 'Build an ordered same-domain history from saved Lookup observations.',
      example: 'whoisleuth timeline first.json second.json latest.json --json',
      boundary: 'The command is offline, accepts 2 to 20 bounded inputs for one domain, retains no filenames or raw registry payloads, and does not treat changed collection conditions as a domain change.',
    },
    collection: { mode: 'offline', scope: 'Reads 2 to 20 saved observations for one domain, capped at 32 MiB in total.' },
    summary: 'Build same-domain history from saved lookups',
    options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('sources', 'file', 2, 20)]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'history',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.lookup-timeline']),
    primaryArtefacts: Object.freeze(['Bounded retained-observation timeline']),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  export: commandSeed({
    reference: {
      description: 'Convert one saved lookup into a versioned evidence report.',
      example: 'whoisleuth export lookup.json --markdown',
      boundary: `Saved Lookup versions 1 and 2 are capped at 8 MiB and scanned for duplicate keys, the prototype-sensitive __proto__ key, and bounded nesting, key, value, and per-container counts before parsing. Current schema-${LOOKUP_EVIDENCE_SCHEMA_VERSION} exports preserve evidence-source attribution and limitations; published v2 schemas ${PUBLISHED_V2_LOOKUP_EVIDENCE_VERSIONS} and exact v1 schema ${V1_PUBLIC_LOOKUP_EVIDENCE_SCHEMA_VERSION} remain readable, while other historical and unreleased shapes are unsupported. Markdown and HTML include a presentation-only generator footer unless --no-attribution is selected; JSON retains bounded generator provenance. Compact output intentionally omits raw registry payloads.`,
    },
    collection: { mode: 'offline', scope: 'Reads one saved Lookup and writes one bounded report.' },
    summary: 'Convert a lookup to an evidence report',
    options: ['--markdown', '--html', '--compact', '--no-attribution'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: Object.freeze([
    constraint({ kind: 'mutually_exclusive', options: ['--markdown', '--html'] }),
    constraint({ kind: 'excludes_all', option: '--compact', excludedOptions: ['--markdown', '--html'] }),
    constraint({ kind: 'requires_any', option: '--no-attribution', requiredOptions: ['--markdown', '--html'] }),
  ]),
    handlerOwner: 'history',
    networkEffect: 'offline',
    common: true,
    schemaIdentifiers: Object.freeze(['whoisleuth.lookup-evidence']),
    primaryArtefacts: Object.freeze(['Portable evidence report']),
    planSupport: false,
    additionalOutputFormats: Object.freeze(['JSON']),
    bootstrapProfile: 'allowed',
  }),
});
