
import { positional, OPTIONAL_FILE_POSITIONAL, constraint, EMPTY_CONSTRAINTS, commandSeed } from './command-definition.mts';

export const NETWORK_COMMAND_DEFINITIONS = Object.freeze({
  "ct-search": commandSeed({
    reference: {
      description: 'Search certificate-transparency observations for one bounded keyword.',
      example: 'whoisleuth ct-search "example brand" --json',
      boundary: 'Certificate observations do not prove website activity, registration ownership, or malicious intent.',
    },
    collection: { scope: 'Accepts one bounded search keyword and queries the fixed certificate-transparency source.' },
    summary: 'Search certificate observations',
    options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('keyword', 'text', 0, 1, [], 'argv_or_stdin')]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'network',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.ct-search']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  posture: commandSeed({
    reference: {
      description: 'Review bounded DNS mail, delegation, and domain-control posture.',
      example: 'whoisleuth posture example.test --mail-profile standard --json',
      boundary: 'Missing or failed DNS observations remain inconclusive. --include-inherited-dns explicitly adds a bounded DMARC tree walk and direct parent-delegation sample; records retain their queried owner and source. No message is sent and receiver enforcement is not inferred.',
    },
    collection: { scope: 'Accepts one domain and performs bounded RDAP, DNS, and conditional MTA-STS HTTPS requests. --include-inherited-dns separately adds ancestor DMARC questions and direct DNS/TCP to sampled parent servers.' },
    summary: 'Review DNS and mail posture',
    options: ['--selectors', '--retired-selectors', '--mail-profile', '--include-inherited-dns', '--json', '--sarif', '--owned-domain', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('domain', 'text', 0, 1, [], 'argv_or_stdin')]),
    constraints: Object.freeze([
    constraint({ kind: 'mutually_exclusive', options: ['--json', '--sarif'] }),
    constraint({ kind: 'requires_all', option: '--sarif', requiredOptions: ['--owned-domain'] }),
  ]),
    handlerOwner: 'network',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.posture']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  http: commandSeed({
    reference: {
      description: 'Inspect one homepage request, redirects, and bounded response metadata.',
      example: 'whoisleuth http example.test --json',
      boundary: 'Requests use the shared public-address and redirect guards. Fixed content-coding and cache-policy metadata describes only the selected response, excludes raw header values, and does not prove caching, transfer savings, performance, privacy, or safety. This is not a rendered browser or vulnerability scan.',
    },
    collection: { scope: 'Accepts one domain and follows only the bounded SSRF-guarded homepage redirect workflow.' },
    summary: 'Inspect one homepage request',
    options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('domain', 'text', 0, 1, [], 'argv_or_stdin')]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'network',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.http']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  tls: commandSeed({
    reference: {
      description: 'Inspect one hostname certificate through a bounded TLS connection.',
      example: 'whoisleuth tls example.test --json',
      boundary: 'One observed connection is point-in-time evidence and does not establish every address, edge, or historical certificate.',
    },
    collection: { scope: 'Accepts one public hostname and opens one bounded certificate connection.' },
    summary: 'Inspect one TLS connection',
    options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('hostname', 'text', 0, 1, [], 'argv_or_stdin')]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'network',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.tls']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "dnssec-validate": commandSeed({
    reference: {
      description: 'Cryptographically validate one authorised DNSSEC chain from a supplied trust anchor through one selected public resolver.',
      example: 'whoisleuth dnssec-validate example.test --resolver "$PUBLIC_RESOLVER_IP" --trust-anchor anchor.json --owned-or-authorized --json',
      boundary: 'This isolated action is never invoked by Lookup, Bulk, monitoring, or recipes. It caps DNS queries, aliases, delegations, bytes, and duration; transport and validation failures remain separate, and secure is not a general safety verdict.',
    },
    collection: { scope: 'Accepts one authorised domain, one public resolver IP, and one local trust-anchor file; DNS-over-TCP validation is capped at 32 queries and 15 seconds.' },
    summary: 'Validate an authorised DNSSEC chain',
    options: ['--resolver', '--trust-anchor', '--owned-or-authorized', '--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('domain', 'text', 1, 1)]),
    constraints: Object.freeze([
    constraint({ kind: 'required', options: ['--resolver', '--trust-anchor', '--owned-or-authorized'] }),
  ]),
    handlerOwner: 'network',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.dnssec-chain-validation', 'whoisleuth.dnssec-trust-anchor']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "mail-transport": commandSeed({
    reference: {
      description: 'Review selected authorised MX endpoints, DNSSEC-qualified TLSA evidence, SMTP capabilities, and optional STARTTLS certificates.',
      example: 'whoisleuth mail-transport selected-mx.json --resolver "$PUBLIC_RESOLVER_IP" --trust-anchor anchor.json --owned-or-authorized --active-probe --json',
      boundary: 'This isolated action probes at most three selected MX hosts sequentially, reports selection, public revalidation, connection, and address authentication separately, sends only EHLO and optional STARTTLS, never retries, and performs no authentication, relay, recipient, mailbox, catch-all, or message test. If a DANE-TA TLSA usage 2 association is published, active collection retains only the leaf certificate and leaves that comparison partial without certificate-path construction and trust-anchor path validation. SMTP relay PKIX-TA usage 0 and PKIX-EE usage 1 records remain unsupported and cannot complete SMTP DANE assurance; a separate usage 3 match remains eligible.',
    },
    collection: { scope: 'Accepts at most three selected authorised MX hosts, uses one public resolver, and performs sequential bounded SMTP connections with no retries.' },
    summary: 'Review selected authorised SMTP transports',
    options: ['--resolver', '--trust-anchor', '--owned-or-authorized', '--active-probe', '--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: Object.freeze([
    constraint({ kind: 'required', options: ['--resolver', '--trust-anchor', '--owned-or-authorized', '--active-probe'] }),
  ]),
    handlerOwner: 'network',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.mail-transport.input', 'whoisleuth.cli.mail-transport-review']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
});
