import { RISK_CALIBRATION_DATASET_SCHEMA, RISK_CALIBRATION_REPORT_SCHEMA } from '../packages/contracts/risk-calibration.mts';
import { positional, NO_POSITIONALS, OPTIONAL_FILE_POSITIONAL, constraint, EMPTY_CONSTRAINTS, commandSeed, text } from './command-definition.mts';

export const SUPPORT_COMMAND_DEFINITIONS = Object.freeze({
  completion: commandSeed({
    reference: {
      description: 'Print a static shell-completion script for the installed CLI.',
      example: 'whoisleuth completion zsh > ~/.zfunc/_whoisleuth',
      boundary: 'Generation is offline and writes only the script to stdout. The command never modifies shell configuration.',
    },
    collection: { scope: 'Prints one static script and changes no shell configuration.' },
    summary: 'Print shell completion',
    options: [],
    positionals: Object.freeze([positional('shell', 'enum', 1, 1, ['bash', 'zsh', 'fish', 'powershell'])]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze([]),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  doctor: commandSeed({
    reference: {
      description: 'Check the supported runtime and local terminal capabilities.',
      example: 'whoisleuth doctor --json',
      boundary: 'The default check is offline. Public DNS and port 43 checks run only when --network is explicitly supplied.',
    },
    collection: { scope: 'Network access is opt-in with --network and is limited to fixed public DNS, HTTPS, and WHOIS diagnostics.' },
    summary: 'Check the local CLI runtime',
    options: ['--network', '--json', '--quiet', '--no-color'],
    positionals: NO_POSITIONALS,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'conditional_network',
    common: true,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.doctor']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  commands: commandSeed({
    reference: {
      description: 'List the installed command contracts in terminal or versioned JSON form.',
      example: 'whoisleuth commands --json',
      boundary: 'Catalogue generation is offline. It reports declared command modes and limits without executing collection or inspecting local evidence.',
    },
    collection: { scope: 'Reads the embedded command catalogue and performs no collection.' },
    summary: 'List installed command contracts',
    options: ['--common', '--group', '--mode', '--json', '--quiet', '--no-color'],
    positionals: NO_POSITIONALS,
    constraints: Object.freeze([]),
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: true,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.command-catalogue']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  manual: commandSeed({
    reference: {
      description: 'Print a generated roff manual page for local installation.',
      example: 'whoisleuth manual | man -l -',
      boundary: 'Generation is offline and derives from the same command catalogue as focused help.',
    },
    collection: { scope: 'Builds documentation from the embedded command catalogue.' },
    summary: 'Print the generated manual page',
    options: [],
    positionals: NO_POSITIONALS,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze([]),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "registry-support": commandSeed({
    reference: {
      description: 'Explain the local registry capability profile for one domain or suffix.',
      example: 'whoisleuth registry-support example.test --json',
      boundary: 'This command is offline. Catalogue coverage does not test live reachability or decide registration or availability.',
    },
    collection: { scope: 'Reads the embedded registry capability catalogue for one domain or suffix.' },
    summary: 'Explain local registry coverage',
    options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('domain-or-suffix', 'text', 0, 1, [], 'argv_or_stdin')]),
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.registry-support', 'whoisleuth.registry-standards-coverage']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "registry-doctor": commandSeed({
    reference: {
      description: 'Compare a saved Lookup registry result with the reviewed local capability profile.',
      example: 'whoisleuth registry-doctor lookup.json --json',
      boundary: 'The command is offline. It distinguishes expected access constraints from collection results and does not contact a live registry.',
    },
    collection: { scope: 'Reads one saved Lookup and the embedded registry capability catalogue.' },
    summary: 'Diagnose saved registry collection',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.registry-doctor']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "registry-cohort": commandSeed({
    reference: {
      description: 'Build privacy-safe suffix and capability-profile timelines from saved observations or retained cohort reports.',
      example: 'whoisleuth registry-cohort saved-lookups.jsonl --json',
      boundary: 'This command is offline and omits domains, queries, and raw evidence. Input families cannot be mixed, and retained samples are never assumed independent.',
    },
    collection: { scope: 'Reads at most 500 saved Lookups or retained cohort reports from one unmixed family and emits bounded target-free timelines.' },
    summary: 'Build target-free registry quality timelines',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.registry-cohort']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "registry-scaffold": commandSeed({
    reference: {
      description: 'Create a bounded synthetic WHOIS fixture scaffold for one existing capability profile.',
      example: 'whoisleuth registry-scaffold --profile nic-io-colon --suffix ac --scenario registered',
      boundary: 'The output is a sanitised template only. Its command-owned --profile selects fixture capability, --config is rejected, and contributors must not paste live responses or personal registration data into fixtures.',
    },
    collection: { scope: 'Reads the embedded registry capability catalogue and prints one synthetic fixture template.' },
    summary: 'Create a sanitised registry fixture scaffold',
    options: ['--profile', '--suffix', '--scenario'],
    optionOverrides: { '--profile': text('Select a catalogue profile; find its ID with registry-support <suffix> --json.', true) },
    positionals: NO_POSITIONALS,
    constraints: Object.freeze([
    constraint({ kind: 'required', options: ['--profile', '--suffix', '--scenario'] }),
  ]),
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze([]),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'command_owned',
  }),
  "risk-calibrate": commandSeed({
    reference: {
      description: 'Replay reviewed labels against the current explainable Risk model.',
      example: 'whoisleuth risk-calibrate calibration.json --summary-json',
      boundary: 'Calibration is offline and diagnostic. The summary form omits record identifiers, domains, and evidence; neither form trains, tunes, or changes the scoring model automatically.',
    },
    collection: { scope: 'Reads one bounded reviewed-label dataset and changes no model or evidence.' },
    summary: 'Replay reviewed Risk labels offline',
    options: ['--json', '--summary-json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: Object.freeze([
    constraint({ kind: 'mutually_exclusive', options: ['--json', '--summary-json'] }),
  ]),
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze([RISK_CALIBRATION_DATASET_SCHEMA, RISK_CALIBRATION_REPORT_SCHEMA]),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "lookalike-calibrate": commandSeed({
    reference: {
      description: 'Summarise reviewed candidate dispositions by mutation family without retaining domains.',
      example: 'whoisleuth lookalike-calibrate reviewed-candidates.json --json',
      boundary: 'Calibration is offline and diagnostic. It omits candidate identifiers, domains, notes, and evidence and never tunes generation or filtering automatically.',
    },
    collection: { scope: 'Reads at most 5,000 reviewed candidate labels from one dataset capped at 2 MiB.' },
    summary: 'Summarise reviewed lookalike yield offline',
    options: ['--json', '--quiet', '--no-color'],
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: EMPTY_CONSTRAINTS,
    handlerOwner: 'support',
    networkEffect: 'offline',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.lookalike-calibration-input', 'whoisleuth.lookalike-calibration']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
});
