import { INVESTIGATION_PLAN_RECIPES, RUNNABLE_INVESTIGATION_PLAN_RECIPES } from './investigation-recipes.mts';
import { positional, OPTIONAL_FILE_POSITIONAL, constraint, commandSeed, integer, BASE_INTEGER_RANGE, file, optionDefinition } from './command-definition.mts';
import { DOMAIN_FEED_CATALOGUE } from '../packages/monitoring/domain-feed.mts';

export const WORKFLOW_COMMAND_DEFINITIONS = Object.freeze({
  'domain-feed': commandSeed({
    reference: { description: 'Review exact hosts or literal terms in a selected local plain-domain feed.',
      example: 'whoisleuth domain-feed review tif-mini feed.txt --select host:candidate.example --json',
      boundary: 'Always available offline. Reads one explicit local regular file; never downloads a feed, performs a Lookup, changes scores, retains candidates or enables a schedule. Streams at most 256 MiB and 10 million physical rows with 1,024-byte lines and a ten-minute deadline; retains at most 200 matched hosts. Repeat --select host:<hostname> or term:<literal> for at most 200 exact hosts and 20 literal terms of 3–80 characters. Matching never treats a parent as equivalent or executes a regular expression. Review emits the full raw-byte digest, separate declared file/local clocks, unknown per-host clocks and omissions. watch-input also requires a candidate-watch-input v1 context file with an empty candidates array, and emits that existing format for a separate watchlist-review plan/export. Inclusion is not a maliciousness, activity, ownership or availability verdict.' },
    collection: { scope: 'Local raw file: 256 MiB, 10 million physical rows, 1,024 bytes per line, ten minutes; 200 retained hosts, 20 literal terms, no requests.' },
    summary: 'Review a selected local plain-domain feed', options: ['--select', '--json', '--quiet', '--no-color'],
    optionOverrides: { '--select': optionDefinition('text', 'Select host:<exact-hostname> or term:<literal-text>; repeat for separate explicit selectors.', { occurrence: 'repeatable', acceptsOptionLikeValue: true }) },
    positionals: Object.freeze([positional('operation', 'enum', 1, 1, ['review', 'watch-input']),
      positional('feed', 'enum', 1, 1, DOMAIN_FEED_CATALOGUE.map(feed => feed.id)), positional('source', 'file', 1, 1), positional('context', 'file', 0, 1)]),
    constraints: Object.freeze([constraint({ kind: 'required', options: ['--select'] })]),
    handlerOwner: 'workflow', networkEffect: 'offline', common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.candidate-watch-input']), primaryArtefacts: Object.freeze(['Bounded feed inclusion review', 'Explicit candidate watch selection']),
    planSupport: true, additionalOutputFormats: Object.freeze([]), bootstrapProfile: 'allowed',
  }),
  'watchlist-review': commandSeed({
    reference: { description: 'Preview or export an explicit candidate selection to a local watchlist.', example: 'whoisleuth watchlist-review plan selection.json --json',
      boundary: 'Reads bounded local JSON only. Plan shows exact domains, duplicates, per-domain outcomes, destination and review priority with zero additional requests. Export emits Watchlist schema 5 without creating a scan or baseline. Neither mode enables collection or scheduling.' },
    collection: { scope: 'At most 2,000 selected candidate domains; no target requests.' },
    summary: 'Review a local candidate watchlist handoff', options: ['--json', '--quiet', '--no-color'],
    positionals: Object.freeze([positional('operation', 'enum', 1, 1, ['plan', 'export']), positional('source', 'file', 0, 1, [], 'argv_or_stdin')]),
    constraints: Object.freeze([]), handlerOwner: 'workflow', networkEffect: 'offline', common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.candidate-watch-input', 'whoisleuth.watchlists']), primaryArtefacts: Object.freeze(['Exact candidate handoff plan', 'Local watchlist export']),
    planSupport: true, additionalOutputFormats: Object.freeze([]), bootstrapProfile: 'allowed',
  }),
  "monitor-once": commandSeed({
    reference: {
      description: 'Collect one bounded owned-domain review and compare it with an optional prior checkpoint.',
      example: 'whoisleuth monitor-once manifest.json --previous previous.json --json --output next.json',
      boundary: 'This is an operator-scheduled one-shot collection, not a daemon. It caps targets and concurrency, retains normalised observations, and never changes domain configuration.',
    },
    collection: { scope: 'Runs deep collection for at most 20 manifest domains with concurrency capped at 3.' },
    summary: 'Run one bounded domain control review',
    options: ['--previous', '--limit', '--concurrency', '--fail-on', '--json', '--junit', '--quiet', '--no-color'],
    optionOverrides: {
      '--concurrency': integer('Set the maximum number of concurrent collection tasks.',
        () => Object.freeze([BASE_INTEGER_RANGE(1, 3)]), () => 2),
    },
    positionals: OPTIONAL_FILE_POSITIONAL,
    constraints: Object.freeze([
    constraint({ kind: 'mutually_exclusive', options: ['--json', '--junit'] }),
  ]),
    handlerOwner: 'workflow',
    networkEffect: 'always_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.domain-control-monitor', 'whoisleuth.domain-control-flight-recorder.input']),
    primaryArtefacts: Object.freeze([]),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "workflow-plan": commandSeed({
    reference: {
      description: 'Build a fixed domain-investigation plan from existing bounded CLI commands.',
      example: 'whoisleuth workflow-plan domain-triage example.test --json',
      boundary: 'Planning is offline and plan-only. It does not execute commands, expand placeholders, read files, make requests, or submit evidence.',
    },
    collection: { scope: 'Builds a fixed typed recipe and executes none of its network or file steps.' },
    summary: 'Plan a fixed investigation recipe',
    options: ['--list', '--explain', '--json', '--quiet', '--no-color'],
    positionals: Object.freeze([
    positional('recipe', 'enum', 0, 1, INVESTIGATION_PLAN_RECIPES),
    positional('subject', 'text', 0, 1),
  ]),
    constraints: Object.freeze([
    constraint({ kind: 'mutually_exclusive', options: ['--list', '--explain'] }),
  ]),
    handlerOwner: 'workflow',
    networkEffect: 'offline',
    common: true,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.investigation-plan', 'whoisleuth.cli.workflow-recipe-catalogue']),
    primaryArtefacts: Object.freeze(['Plan-only workflow document']),
    planSupport: true,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
  "workflow-run": commandSeed({
    reference: {
      description: 'Execute approved steps from a fixed investigation recipe and emit a resumable checkpoint.',
      example: 'whoisleuth workflow-run domain-triage example.test --approve-network --json --output run.json',
      boundary: '--preview validates the checkpoint and shows retained outputs, unresolved inputs and remaining approvals without executing or writing. It cannot be combined with approval, interactive, quiet or output-file flags. Only installed recipe commands can run. Network steps require explicit approval for each invocation. New runs connect compatible earlier outputs using the recipe defaults. Use --use-artifact <step-id>:<input-number>=<earlier-step-id> to override a connection; input numbers start at 1. Repeat --select for remaining placeholders in order, or supply every input for a step to replace its connections with files. Values stay literal and cannot start with a hyphen or invoke a shell. Optional --interactive prompts on terminal stderr for missing inputs; a blank answer pauses. It grants neither network approval nor human-review confirmation. A step declaring human review still requires --confirm-review <step-id> for that invocation. Checkpoints do not grant later approvals. Resumes preserve recorded connections. Content digests identify retained output, not authenticity or freshness. Partial collections pause for review and are not recollected on resume; failed validation or export steps remain retryable. Diagnostics go to stderr. File output holds exclusive adjacent locks and refuses concurrently changed state files.',
    },
    collection: { scope: 'Runs only fixed-recipe steps; network collection requires --approve-network and unresolved analyst selections pause.' },
    summary: 'Execute approved fixed-recipe steps',
    options: ['--select', '--use-artifact', '--confirm-review', '--approve-network', '--resume', '--interactive', '--preview', '--json', '--quiet', '--no-color'],
    optionOverrides: { '--resume': file('Resume the selected workflow checkpoint; approvals must be supplied again.') },
    positionals: Object.freeze([
    positional('recipe', 'enum', 1, 1, RUNNABLE_INVESTIGATION_PLAN_RECIPES),
    positional('subject', 'text', 1, 1),
  ]),
    constraints: Object.freeze([constraint({ kind: 'excludes_all', option: '--preview', excludedOptions: ['--approve-network', '--confirm-review', '--interactive', '--output', '--force', '--quiet'] })]),
    handlerOwner: 'workflow',
    networkEffect: 'conditional_network',
    common: false,
    schemaIdentifiers: Object.freeze(['whoisleuth.cli.investigation-run', 'whoisleuth.cli.investigation-preview']),
    primaryArtefacts: Object.freeze(['Resumable workflow state', 'Offline resume preview']),
    planSupport: false,
    additionalOutputFormats: Object.freeze([]),
    bootstrapProfile: 'allowed',
  }),
});
