<script lang="ts">
  import { goto } from '$app/navigation';
  import { saveCandidateHandoff } from '$lib/candidate-handoff';
  import { deleteWatchlist, exportWatchlists, fieldLabels, formatValue, importWatchlists, loadWatchlists, MAX_WATCHLIST_IMPORT_BYTES, writeWatchlists, type Watchlists } from '$lib/watchlists';

  let watchlists=$state<Watchlists>({});let selected=$state('');let changedOnly=$state(false);let message=$state('');
  const names=$derived(Object.keys(watchlists).sort());const entry=$derived(selected?watchlists[selected]||null:null);const history=$derived(entry?(changedOnly?entry.history.filter(e=>e.changeCount>0):entry.history):[]);
  function refresh(){watchlists=loadWatchlists();if(selected&&!watchlists[selected])selected='';}
  function date(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString();}
  function remove(name:string){if(!confirm(`Delete watchlist "${name}" and its history?`))return;deleteWatchlist(name);refresh();}
  function clearAll(){if(!names.length||!confirm('Delete every saved watchlist and its history?'))return;writeWatchlists({});refresh();}
  async function rescan(name:string){const current=watchlists[name];if(!current)return;const candidates=current.results.map(record=>({domain:String(record.domain),source:name,mutationTypes:Array.isArray(record.mutationTypes)?record.mutationTypes:[]}));saveCandidateHandoff('watchlist',candidates);await goto('/bulk?source=watchlist');}
  async function importFile(event:Event){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];if(!file)return;try{if(file.size>MAX_WATCHLIST_IMPORT_BYTES)throw new Error('Watchlist imports are limited to 2 MB.');const result=importWatchlists(JSON.parse(await file.text()));message=`Imported ${result.added} new and ${result.updated} updated watchlists.`;refresh();}catch(cause){message=cause instanceof Error?cause.message:'Import failed';}finally{input.value='';}}
  refresh();
</script>

<svelte:head><title>Monitor · WHOISleuth</title></svelte:head>
<section class="heading"><div><p class="eyebrow">Monitor</p><h1>Watchlists and history</h1><p>Review browser-local monitoring sets, material changes, and bounded investigation timelines.</p></div><div class="top-actions"><button onclick={exportWatchlists} disabled={!names.length}>Export JSON</button><label>Import JSON<input type="file" accept="application/json,.json" onchange={importFile}></label><button class="danger" onclick={clearAll} disabled={!names.length}>Clear all</button></div></section>
{#if message}<p class="message">{message}</p>{/if}

{#if names.length}
  <section class="watchlists card"><div class="table-wrap"><table><thead><tr><th>Name</th><th>Domains</th><th>Checks</th><th>Latest changes</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{#each names as name}{@const item=watchlists[name]}{@const latest=item.history.at(-1)}<tr><td><strong>{name}</strong></td><td>{item.results.length}</td><td>{item.history.length}</td><td><span class:changed={(latest?.changeCount||0)>0}>{latest?.changeCount||0}</span></td><td>{date(item.updatedAt)}</td><td><div class="actions"><button onclick={()=>rescan(name)}>Load for re-scan</button><button onclick={()=>{selected=name;changedOnly=false}}>History</button><button class="danger" onclick={()=>remove(name)}>Delete</button></div></td></tr>{/each}</tbody></table></div></section>
{:else}
  <section class="empty card"><h2>No watchlists saved</h2><p>Run a Bulk scan, then save its results to begin a browser-local monitoring timeline.</p><a href="/bulk">Open Bulk analysis →</a></section>
{/if}

{#if entry}
  <section class="history card"><header><div><p class="eyebrow">History</p><h2>{selected}</h2><p>{entry.history.length} retained checks · {entry.results.length} domains</p></div><div><button class:active={changedOnly} aria-pressed={changedOnly} onclick={()=>changedOnly=!changedOnly}>Changes only</button><button onclick={()=>selected=''}>Close</button></div></header>
    <div class="events">{#each [...history].reverse() as event}<article><div class="event-head"><time datetime={event.checkedAt}>{date(event.checkedAt)}</time><span>{event.mode} scan</span><strong class:changed={event.changeCount>0}>{event.changeCount} change{event.changeCount===1?'':'s'}</strong><small>{event.conclusiveCount}/{event.resultCount} conclusive</small></div>{#if event.changes.length}<ul>{#each event.changes as change}<li class={change.tone}><strong>{change.domain}</strong><span>{fieldLabels[change.field]||change.field}</span><small>{formatValue(change.before)} → {formatValue(change.after)}</small></li>{/each}</ul>{:else}<p class="no-change">No material changes detected.</p>{/if}{#if event.omittedChanges}<p class="no-change">{event.omittedChanges} additional changes omitted to keep storage bounded.</p>{/if}</article>{/each}</div>
  </section>
{/if}

<style>.top-actions,.actions,.history header>div:last-child{display:flex;flex-wrap:wrap;gap:7px}.top-actions button,.top-actions label,.actions button,.history button{min-height:38px;padding:0 11px;border:1px solid var(--border);border-radius:9px;background:#101d2f;font-size:.7rem}.top-actions label{display:grid;place-items:center;cursor:pointer}.top-actions input{display:none}.danger{color:var(--danger)}.message{color:var(--accent)}.watchlists,.history{padding:22px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.74rem}th,td{padding:12px 9px;border-top:1px solid var(--border);text-align:left}th{color:var(--muted);font-size:.64rem;text-transform:uppercase}.changed{color:var(--danger)}.empty{display:grid;min-height:300px;place-content:center;padding:30px;text-align:center}.empty p,.history header p,.no-change{color:var(--muted)}.empty a{color:var(--accent);font-weight:700}.history{margin-top:16px}.history header{display:flex;justify-content:space-between;gap:16px}.history h2{margin:0}.history header p{margin:5px 0}.history button.active{color:var(--accent);border-color:#4c8d8a}.events{display:grid;gap:10px;margin-top:18px}.events article{padding:16px;border:1px solid var(--border);border-radius:12px;background:#0a1624}.event-head{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.event-head span,.event-head strong{padding:5px 7px;border:1px solid var(--border);border-radius:99px;font-size:.65rem;text-transform:capitalize}.event-head small{margin-left:auto;color:var(--muted)}ul{display:grid;gap:6px;margin:14px 0 0;padding:0;list-style:none}li{display:grid;grid-template-columns:minmax(150px,1fr) 120px minmax(180px,1fr);gap:10px;padding:8px;border-left:3px solid var(--border);font-size:.7rem}li.danger{border-color:var(--danger)}li.warn{border-color:#f2c46d}li.good{border-color:var(--accent)}li span,li small{color:var(--muted)}@media(max-width:800px){.heading{align-items:start;flex-direction:column}.history header{display:block}.history header>div:last-child{margin-top:12px}.table-wrap{margin-inline:-22px;padding-inline:22px}li{grid-template-columns:1fr} .event-head small{width:100%;margin:0}}</style>
