import { CASE_PORTABILITY_LIFECYCLE_FAMILY } from './case-portability.mts';
import { EXTERNAL_OBSERVATION_INTERCHANGE_LIFECYCLE_FAMILY } from './external-observation-interchange.mts';
import { INVESTIGATION_PORTABILITY_LIFECYCLE_FAMILY } from './investigation-portability.mts';
import { OFFLINE_COMPARISON_LIFECYCLE_FAMILY } from './offline-comparison.mts';
import { CLI_LOOKUP_SCHEMA_LIFECYCLE } from './cli-lookup.mts';
import { DOMAIN_CONTROL_FLIGHT_RECORDER_SCHEMA_LIFECYCLE } from './domain-control-flight-recorder.mts';
import { DOMAIN_CONTROL_SCHEMA_LIFECYCLE } from './domain-control-manifest.mts';
import { DOMAIN_CONTROL_MONITOR_SCHEMA_LIFECYCLE } from './domain-control-monitor.mts';
import { DOMAIN_CONTROL_REVIEW_SCHEMA_LIFECYCLE } from './domain-control-review.mts';
import { RISK_CALIBRATION_SCHEMA_LIFECYCLE } from './risk-calibration.mts';
import { WORKSPACE_PORTABILITY_LIFECYCLE_FAMILY } from './workspace-portability.mts';
import { ANALYST_INTERCHANGE_LIFECYCLE_FAMILY } from './analyst-interchange.mts';
import { INVESTIGATION_PROJECTIONS_LIFECYCLE_FAMILY } from './investigation-projections.mts';
import { MONITORING_PORTABILITY_LIFECYCLE_FAMILY } from './monitoring-portability.mts';
import { RELATIONSHIP_PORTABILITY_LIFECYCLE_FAMILY } from './relationship-portability.mts';
import { TAB_PORTABILITY_LIFECYCLE_FAMILY } from './tab-portability.mts';
import { PRIVACY_DATA_FLOW_CATALOGUE_LIFECYCLE_FAMILY } from './privacy-data-flow-catalogue.mts';
import { defineSchemaLifecycleRegistry } from './schema-lifecycle.mts';

export const SCHEMA_LIFECYCLE_REGISTRY = defineSchemaLifecycleRegistry([
  CASE_PORTABILITY_LIFECYCLE_FAMILY,
  INVESTIGATION_PORTABILITY_LIFECYCLE_FAMILY,
  EXTERNAL_OBSERVATION_INTERCHANGE_LIFECYCLE_FAMILY,
  OFFLINE_COMPARISON_LIFECYCLE_FAMILY,
  DOMAIN_CONTROL_SCHEMA_LIFECYCLE,
  DOMAIN_CONTROL_REVIEW_SCHEMA_LIFECYCLE,
  DOMAIN_CONTROL_FLIGHT_RECORDER_SCHEMA_LIFECYCLE,
  DOMAIN_CONTROL_MONITOR_SCHEMA_LIFECYCLE,
  CLI_LOOKUP_SCHEMA_LIFECYCLE,
  RISK_CALIBRATION_SCHEMA_LIFECYCLE,
  WORKSPACE_PORTABILITY_LIFECYCLE_FAMILY,
  TAB_PORTABILITY_LIFECYCLE_FAMILY,
  MONITORING_PORTABILITY_LIFECYCLE_FAMILY,
  INVESTIGATION_PROJECTIONS_LIFECYCLE_FAMILY,
  RELATIONSHIP_PORTABILITY_LIFECYCLE_FAMILY,
  ANALYST_INTERCHANGE_LIFECYCLE_FAMILY,
  PRIVACY_DATA_FLOW_CATALOGUE_LIFECYCLE_FAMILY,
]);
