export {
  MAX_WEB_CAPTURE_MANIFEST_BYTES,
  WEB_CAPTURE_MANIFEST_SCHEMA,
  WEB_CAPTURE_MANIFEST_VERSION,
  WEB_CAPTURE_SUMMARY_SCHEMA,
  WEB_CAPTURE_SUMMARY_VERSION,
} from './analyst-interchange.mts';
export const WEB_CAPTURE_DOM_DIGEST_SCHEMA = 'whoisleuth.dom-digest';
export const WEB_CAPTURE_DOM_DIGEST_VERSION = 1;
export const WEB_CAPTURE_COMPARISON_SCHEMA = 'whoisleuth.web-capture-comparison';
export const WEB_CAPTURE_COMPARISON_VERSION = 3;
export const MAX_WEB_CAPTURE_DOM_DIGEST_BYTES = 1024 * 1024;
export const MAX_WEB_CAPTURE_SCREENSHOT_BYTES = 10 * 1024 * 1024;
export const MAX_WEB_CAPTURE_DOM_ELEMENTS = 20_000;
export const MAX_WEB_CAPTURE_DOM_PROJECTION_CHARACTERS = 256 * 1024;
export const MAX_WEB_CAPTURE_VISIBLE_TEXT_BYTES = 256 * 1024;
