import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readBoundedRegularFile } from '../lib/bounded-file.mts';
import {
  jsonRecordOrEmpty as record,
  sha256Text as moduleDigest,
} from './maintainer-tool-helpers.mts';

const SOURCE_VERSION = '2026.08.03';
const SOURCE_RELEASED_AT = '2026-08-03T18:55:09.067Z';
const SOURCE_SHA256 = '16acee8334e59e44ccbaed4da7d02b409144061542b64ad74a9443fb7842a828';
const SOURCE_URL = 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json';
const OUTPUT_PATH = 'lib/generated/cisa-kev-catalog.mts';
const OUTPUT_DIGEST_PATH = 'lib/generated/cisa-kev-catalog.sha256';
const MAX_SOURCE_BYTES = 5 * 1024 * 1024;
const MAX_OUTPUT_BYTES = 128 * 1024;
const MAX_ENTRIES = 10_000;
const CVE_RE = /^CVE-[0-9]{4}-[0-9]{4,}$/;

type UnknownRecord = Record<string, unknown>;
type WritableLike = { write(value: string): unknown };
type CatalogMode = 'check' | 'write';
type MainOptions = Readonly<{
  repositoryRoot?: string;
  stdout?: WritableLike;
  stderr?: WritableLike;
}>;

function parseArguments(args: readonly string[]): { mode: CatalogMode; source: string } {
  const sourceIndex = args.indexOf('--source');
  const modes = (['--check', '--write'] as const).filter((mode) => args.includes(mode));
  if (modes.length !== 1 || sourceIndex === -1 || !args[sourceIndex + 1] || args.length !== 3) {
    throw new TypeError('Usage: npm run catalog:kev -- --source <pinned-known-exploited-vulnerabilities.json> <--check|--write>');
  }
  const mode = modes[0];
  const source = args[sourceIndex + 1];
  if (!mode || !source) throw new TypeError('The catalogue mode and source are required.');
  return { mode: mode.slice(2) as CatalogMode, source };
}

async function readBoundedText(filename: string, maxBytes: number): Promise<string> {
  try {
    return (await readBoundedRegularFile(filename, {
      minimumBytes: 1,
      maximumBytes: maxBytes,
      label: 'Pinned KEV source',
      allowSymbolicLink: true,
    })).toString('utf8');
  } catch {
    throw new TypeError(`${filename} is missing or exceeds its byte limit.`);
  }
}

function projectCatalogue(value: unknown, expectedVersion: string, expectedReleasedAt: string): string[] {
  const source = record(value);
  if (source.catalogVersion !== expectedVersion || source.dateReleased !== expectedReleasedAt) {
    throw new Error('CISA KEV catalogue version or release date does not match the pinned metadata.');
  }
  const vulnerabilities = Array.isArray(source.vulnerabilities) ? source.vulnerabilities : [];
  if (vulnerabilities.length === 0 || vulnerabilities.length > MAX_ENTRIES) {
    throw new RangeError(`CISA KEV catalogue must contain between 1 and ${MAX_ENTRIES} records.`);
  }
  const identifiers = new Set<string>();
  for (const item of vulnerabilities) {
    const cve = record(item).cveID;
    if (typeof cve !== 'string' || !CVE_RE.test(cve)) throw new TypeError('CISA KEV catalogue contains an invalid CVE identifier.');
    identifiers.add(cve);
  }
  if (identifiers.size !== vulnerabilities.length || source.count !== vulnerabilities.length) {
    throw new Error('CISA KEV catalogue count or uniqueness check failed.');
  }
  return [...identifiers].sort();
}

function projectSource(sourceText: string): string[] {
  const sourceHash = createHash('sha256').update(sourceText).digest('hex');
  if (sourceHash !== SOURCE_SHA256) {
    throw new Error(`CISA KEV catalogue digest mismatch: expected ${SOURCE_SHA256}, received ${sourceHash}.`);
  }
  return projectCatalogue(JSON.parse(sourceText), SOURCE_VERSION, SOURCE_RELEASED_AT);
}

function renderModule(identifiers: readonly string[]): string {
  return `// Generated by tools/cisa-kev-catalog.mts from the pinned CISA KEV feed.\n`
    + `// United States Government work; do not edit by hand.\n\n`
    + `const CISA_KEV_CATALOG = Object.freeze({\n`
    + `  catalogVersion: ${JSON.stringify(SOURCE_VERSION)},\n`
    + `  releasedAt: ${JSON.stringify(SOURCE_RELEASED_AT)},\n`
    + `  sourceSha256: ${JSON.stringify(SOURCE_SHA256)},\n`
    + `  sourceUrl: ${JSON.stringify(SOURCE_URL)},\n`
    + `  identifiers: Object.freeze(${JSON.stringify(identifiers, null, 2)}),\n`
    + `});\n\n`
    + `export { CISA_KEV_CATALOG };\n`;
}

async function main(args = process.argv.slice(2), options: MainOptions = {}): Promise<number> {
  const stdout = options.stdout || process.stdout;
  const stderr = options.stderr || process.stderr;
  try {
    const parsed = parseArguments(args);
    const repositoryRoot = resolve(options.repositoryRoot || process.cwd());
    const sourceText = await readBoundedText(resolve(repositoryRoot, parsed.source), MAX_SOURCE_BYTES);
    const identifiers = projectSource(sourceText);
    const expected = renderModule(identifiers);
    if (Buffer.byteLength(expected, 'utf8') > MAX_OUTPUT_BYTES) throw new RangeError('Projected CISA KEV catalogue exceeds its output byte limit.');

    const outputPath = resolve(repositoryRoot, OUTPUT_PATH);
    const outputDigestPath = resolve(repositoryRoot, OUTPUT_DIGEST_PATH);
    if (parsed.mode === 'check') {
      const current = await readBoundedText(outputPath, MAX_OUTPUT_BYTES);
      const currentDigest = (await readBoundedText(outputDigestPath, 80)).trim();
      if (current !== expected || currentDigest !== moduleDigest(current)) {
        throw new Error('Generated CISA KEV catalogue is stale. Re-run the catalogue command with --write.');
      }
      stdout.write(`CISA KEV catalogue: pass (${identifiers.length} identifiers)\n`);
      return 0;
    }

    await writeFile(outputPath, expected, 'utf8');
    await writeFile(outputDigestPath, `${moduleDigest(expected)}\n`, 'utf8');
    stdout.write(`Wrote CISA KEV catalogue to ${OUTPUT_PATH}.\n`);
    return 0;
  } catch (error) {
    stderr.write(`${error instanceof Error ? error.message : 'CISA KEV catalogue maintenance failed.'}\n`);
    return 2;
  }
}

const invokedAsScript = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedAsScript) process.exitCode = await main();

export {
  MAX_OUTPUT_BYTES,
  MAX_SOURCE_BYTES,
  OUTPUT_DIGEST_PATH,
  OUTPUT_PATH,
  SOURCE_RELEASED_AT,
  SOURCE_SHA256,
  SOURCE_URL,
  SOURCE_VERSION,
  main,
  moduleDigest,
  parseArguments,
  projectCatalogue,
  projectSource,
  renderModule,
};
