<script lang="ts">
  import { activeProfileId, deleteProfile, exportProfiles, importProfiles, loadProfiles, MAX_PROFILE_IMPORT_BYTES, parseList, setActiveProfile, upsertProfile, type BrandProfile } from '$lib/brand-profiles';
  type AuditResult={domain:string;report:any|null;error:string};
  let profiles=$state<BrandProfile[]>([]);let activeId=$state('');let editing=$state('');let showForm=$state(false);let message=$state('');let auditing=$state(false);let auditResults=$state<AuditResult[]>([]);
  let name=$state(''),official=$state(''),products=$state(''),tlds=$state('com, net, org'),partners=$state(''),allowDomains=$state(''),allowRegistrars=$state(''),selectors=$state(''),trademarkOwner=$state(''),trademarkRegistration=$state(''),faviconHash=$state(''),faviconPHash=$state('');
  const active=$derived(profiles.find(p=>p.id===activeId)||null);
  function refresh(){profiles=loadProfiles();activeId=activeProfileId();if(activeId&&!profiles.some(p=>p.id===activeId)){activeId='';setActiveProfile('');}}
  function clearForm(){editing='';name='';official='';products='';tlds='com, net, org';partners='';allowDomains='';allowRegistrars='';selectors='';trademarkOwner='';trademarkRegistration='';faviconHash='';faviconPHash='';showForm=true;}
  function edit(profile:BrandProfile){editing=profile.id;name=profile.name;official=profile.officialDomains.join('\n');products=profile.productNames.join(', ');tlds=profile.tlds.join(', ');partners=profile.approvedPartnerDomains.join('\n');allowDomains=profile.allowlistedDomains.join('\n');allowRegistrars=profile.allowlistedRegistrars.join(', ');selectors=profile.dkimSelectors.join(', ');trademarkOwner=profile.trademarkOwner;trademarkRegistration=profile.trademarkRegistration;faviconHash=profile.officialFaviconHash;faviconPHash=profile.officialFaviconPHash;showForm=true;}
  function save(){try{const profile=upsertProfile({name,officialDomains:parseList(official,true),productNames:parseList(products),tlds:parseList(tlds,true),approvedPartnerDomains:parseList(partners,true),allowlistedDomains:parseList(allowDomains,true),allowlistedRegistrars:parseList(allowRegistrars),dkimSelectors:parseList(selectors,true),trademarkOwner,trademarkRegistration,officialFaviconHash:faviconHash,officialFaviconPHash:faviconPHash},editing);message=`Saved "${profile.name}" and set it active.`;showForm=false;refresh();}catch(cause){message=cause instanceof Error?cause.message:'Could not save profile.';}}
  function remove(profile:BrandProfile){if(!confirm(`Delete brand profile "${profile.name}"?`))return;deleteProfile(profile.id);auditResults=[];refresh();}
  function activate(id:string){activeId=id;setActiveProfile(id);auditResults=[];}
  async function fetchFavicon(){const domain=parseList(official,true)[0];if(!domain){message='Enter an official domain first.';return;}message='Fetching official favicon…';try{const response=await fetch(`/api/availability?q=${encodeURIComponent(domain)}`);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Favicon lookup failed');faviconHash=body.faviconHash||'';faviconPHash=body.faviconPHash||'';message=faviconHash?`Captured favicon evidence for ${domain}.`:`No favicon found for ${domain}.`;}catch(cause){message=cause instanceof Error?cause.message:'Favicon lookup failed';}}
  async function audit(){if(!active?.officialDomains.length)return;auditing=true;auditResults=[];message=`Auditing ${active.officialDomains.length} official domains…`;const domains=active.officialDomains.slice(0,20);let cursor=0;const next:AuditResult[]=new Array(domains.length);const worker=async()=>{while(cursor<domains.length){const index=cursor++,domain=domains[index];try{const params=new URLSearchParams({q:domain});if(active.dkimSelectors.length)params.set('selectors',active.dkimSelectors.join(','));const response=await fetch(`/api/domain-posture?${params}`);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Audit failed (${response.status})`);next[index]={domain,report:body,error:''};}catch(cause){next[index]={domain,report:null,error:cause instanceof Error?cause.message:'Audit failed'};}}};await Promise.all(Array.from({length:Math.min(3,domains.length)},worker));auditResults=next;auditing=false;message=`Audited ${next.filter(v=>v.report).length}/${domains.length} official domains.`;}
  async function importFile(event:Event){const input=event.currentTarget as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>MAX_PROFILE_IMPORT_BYTES)throw new Error('Profile imports are limited to 2 MB.');const result=importProfiles(JSON.parse(await file.text()));message=`Imported ${result.added} new and ${result.updated} updated profiles.`;refresh();}catch(cause){message=cause instanceof Error?cause.message:'Import failed';}finally{input.value='';}}
  refresh();
</script>

<svelte:head><title>Brands · WHOISleuth</title></svelte:head>
<section class="heading"><div><p class="eyebrow">Protect</p><h1>Brand profiles</h1><p>Manage official assets, allowlists, comparison context, and owned-domain posture.</p></div><div class="top-actions"><button class="primary" onclick={clearForm}>New profile</button><button onclick={exportProfiles} disabled={!profiles.length}>Export JSON</button><label>Import JSON<input type="file" accept="application/json,.json" onchange={importFile}></label></div></section>
{#if message}<p class="message">{message}</p>{/if}
{#if profiles.length}<section class="profiles">{#each profiles as profile}<article class="profile card" class:active={profile.id===activeId}><header><div><p class="eyebrow">{profile.id===activeId?'Active profile':'Saved profile'}</p><h2>{profile.name}</h2></div><input type="radio" name="active-profile" aria-label={`Set ${profile.name} active`} checked={profile.id===activeId} onchange={()=>activate(profile.id)}></header><p>{profile.officialDomains.length} official · {profile.approvedPartnerDomains.length} partners · {profile.allowlistedDomains.length} allowlisted</p><div class="chips">{#each profile.officialDomains.slice(0,6) as domain}<span>{domain}</span>{/each}</div><footer><button onclick={()=>edit(profile)}>Edit</button><button class="danger" onclick={()=>remove(profile)}>Delete</button></footer></article>{/each}</section>{:else}<section class="empty card"><h2>No brand profiles saved</h2><p>Create a profile to establish official domains and trusted infrastructure.</p></section>{/if}

{#if showForm}<section class="form card"><header><h2>{editing?'Edit profile':'New profile'}</h2><button onclick={()=>showForm=false}>Close</button></header><div class="form-grid"><label>Brand name<input bind:value={name}></label><label>Preferred TLDs<input bind:value={tlds}></label><label class="wide">Official domains<textarea bind:value={official}></textarea></label><label>Product names<input bind:value={products}></label><label>DKIM selectors<input bind:value={selectors}></label><label class="wide">Approved partner domains<textarea bind:value={partners}></textarea></label><label class="wide">Allowlisted domains<textarea bind:value={allowDomains}></textarea></label><label>Allowlisted registrars<input bind:value={allowRegistrars}></label><label>Trademark owner<input bind:value={trademarkOwner}></label><label>Trademark registration<input bind:value={trademarkRegistration}></label><label class="wide">Official favicon hash<div class="favicon"><input bind:value={faviconHash} readonly placeholder="Not captured"><button onclick={fetchFavicon}>Fetch from official domain</button></div></label></div><footer><button class="primary" onclick={save}>Save profile</button><button onclick={()=>showForm=false}>Cancel</button></footer></section>{/if}

{#if active}<section class="audit card"><header><div><p class="eyebrow">Prevention</p><h2>Owned-domain posture</h2><p>Audit SPF, DMARC, MTA-STS, TLS-RPT, BIMI, CAA, DNSSEC, and supplied DKIM selectors.</p></div><button class="primary" onclick={audit} disabled={auditing||!active.officialDomains.length}>{auditing?'Auditing…':'Audit official domains'}</button></header>{#if auditResults.length}<div class="audit-results">{#each auditResults as item}<article><h3>{item.domain}</h3>{#if item.error}<p class="error">{item.error}</p>{:else}<p class="counts">{item.report.summary.danger||0} action · {item.report.summary.warning||0} review · {item.report.summary.pass||0} pass</p><div class="checks">{#each item.report.checks as check}<details class={check.status}><summary><span>{check.label}</span><strong>{check.status}</strong></summary><p>{check.summary}</p>{#if check.detail}<p>{check.detail}</p>{/if}{#if check.remediation}<p><b>Next:</b> {check.remediation}</p>{/if}{#if check.records?.length}<pre>{check.records.join('\n')}</pre>{/if}</details>{/each}</div>{/if}</article>{/each}</div>{/if}</section>{/if}

<style>.top-actions,.profile footer,.form footer{display:flex;flex-wrap:wrap;gap:7px}.top-actions button,.top-actions label,.profile button,.form button{min-height:38px;padding:0 11px;border:1px solid var(--border);border-radius:9px;background:#101d2f;font-size:.7rem}.top-actions label{display:grid;place-items:center}.top-actions input{display:none}.message{color:var(--accent)}.profiles{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.profile{padding:20px}.profile.active{border-color:#4c8d8a}.profile header,.form header,.audit header{display:flex;justify-content:space-between;gap:16px}.profile h2,.form h2,.audit h2{margin:0}.profile header input{width:18px;min-height:auto}.profile>p,.audit header p,.empty p{color:var(--muted)}.chips{display:flex;flex-wrap:wrap;gap:5px;margin:14px 0}.chips span{padding:5px 7px;border:1px solid var(--border);border-radius:99px;font-size:.65rem}.danger{color:var(--danger)}.empty{display:grid;min-height:260px;place-content:center;padding:30px;text-align:center}.form,.audit{margin-top:16px;padding:22px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:18px 0}.form-grid label{font-size:.7rem;font-weight:700}.form-grid input,.form-grid textarea{display:block;width:100%;margin-top:6px}.form-grid textarea{min-height:82px;padding:10px;border:1px solid var(--border);border-radius:10px;background:#050e19bf}.wide{grid-column:span 2}.favicon{display:grid;grid-template-columns:1fr auto;gap:7px}.audit>header>button{align-self:start}.audit-results{display:grid;gap:12px;margin-top:18px}.audit-results>article{padding:16px;border:1px solid var(--border);border-radius:12px;background:#0a1624}.audit-results h3{margin:0}.counts{color:var(--muted)}.checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.checks details{padding:10px;border:1px solid var(--border);border-left:3px solid var(--border);border-radius:9px}.checks details.danger{border-left-color:var(--danger)}.checks details.warning{border-left-color:#f2c46d}.checks details.pass{border-left-color:var(--accent)}.checks summary{display:flex;justify-content:space-between;cursor:pointer}.checks summary strong{text-transform:capitalize}.checks p{color:var(--muted);font-size:.7rem}.checks pre{overflow:auto;font-size:.65rem}@media(max-width:750px){.heading{align-items:start;flex-direction:column}.profiles,.form-grid,.checks{grid-template-columns:1fr}.wide{grid-column:auto}.favicon{grid-template-columns:1fr}.audit header{display:block}.audit header button{margin-top:12px}}</style>
