export {
  BRAND_MARK_VIEWBOX, BRAND_MARK_LENS, BRAND_MARK_LINKS, BRAND_MARK_NODES,
  BRAND_WORDMARK_VIEWBOX, BRAND_WORDMARK_PRIMARY, BRAND_WORDMARK_SECONDARY,
  BRAND_PALETTE, brandMarkSvg, brandLogoSvg,
} from '../../../packages/contracts/brand-identity.mts';
