import { isValidEmailAddress } from './analysis/utils.js';

export interface Contact{name?:string|null;org?:string|null;email?:string|null;[key:string]:unknown}
export interface AbuseEvidence{abuseEmail?:string|null;hasMx?:boolean|null;activityStatus?:string|null;privacyProtected?:boolean|null;domainAgeDays?:number|null}
function validEmail(value:unknown){const email=typeof value==='string'?value.trim():'';return isValidEmailAddress(email)?email:null;}
function age(days:unknown){if(typeof days!=='number'||!Number.isFinite(days))return null;if(days<60)return`${Math.round(days)} days ago`;if(days<365)return`${Math.round(days/30)} months ago`;return`${(days/365.25).toFixed(1)} years ago`;}
export function buildOutreachDraft(domain:string,contact:Contact){const greeting=contact.name||contact.org||'there';return[`Hi ${greeting},`,'',`I came across ${domain} and wanted to ask whether you would be open to discussing a potential sale.`,'','Would you be willing to share an asking price, or are you open to receiving an offer?','','Best regards,'].join('\n');}
export function buildAbuseDraft(domain:string,evidence:AbuseEvidence){const signals:string[]=[];if(evidence.hasMx)signals.push('mail infrastructure is configured');if(evidence.activityStatus==='active')signals.push('the domain is actively serving a website');if(evidence.privacyProtected)signals.push('registration details use privacy protection');const registered=age(evidence.domainAgeDays);if(registered)signals.push(`the domain was registered ${registered}`);const lines=['Hello,','',`I am reporting ${domain} as a suspected phishing or brand-impersonation registration.`];if(signals.length)lines.push('',`Observed indicators: ${signals.join('; ')}.`);lines.push('','This domain resembles a brand I am responsible for and does not appear to be affiliated with it. Please investigate under your abuse and acceptable-use policies.','','Thank you,');return lines.join('\n');}
export function outreachAction(domain:string,contact:Contact|null|undefined){const email=validEmail(contact?.email);if(!email||!contact)return null;const body=buildOutreachDraft(domain,contact);return{email,body,mailto:`mailto:${email}?${new URLSearchParams({subject:`Inquiry about ${domain}`,body})}`};}
export function abuseAction(domain:string,evidence:AbuseEvidence|null|undefined){const email=validEmail(evidence?.abuseEmail);if(!email||!evidence)return null;const body=buildAbuseDraft(domain,evidence);return{email,body,mailto:`mailto:${email}?${new URLSearchParams({subject:`Abuse report - suspected phishing domain: ${domain}`,body})}`};}
