export const SHORTLIST_KEY='whois-rdap-shortlist-v1';
export const MAX_SHORTLIST_IMPORT_BYTES=2*1024*1024;
const MAX_SHORTLIST_ENTRIES=500;
export interface ShortlistRecord{domain:string;availability:string;riskScore:number|null;opportunityScore:number|null;registrarName?:string;activityStatus?:string|null;mutationTypes?:string[];savedAt:string;[key:string]:unknown}
function normalize(value:any):ShortlistRecord|null{const domain=String(value?.domain||'').trim().toLowerCase();if(!domain||domain.length>253)return null;return{...value,domain,availability:String(value?.availability||'unknown'),riskScore:Number.isFinite(value?.riskScore)?value.riskScore:null,opportunityScore:Number.isFinite(value?.opportunityScore)?value.opportunityScore:null,mutationTypes:Array.isArray(value?.mutationTypes)?value.mutationTypes.slice(0,30).map(String):[],savedAt:String(value?.savedAt||new Date().toISOString())};}
export function loadShortlist():ShortlistRecord[]{try{const parsed=JSON.parse(localStorage.getItem(SHORTLIST_KEY)||'[]');if(!Array.isArray(parsed))return[];return parsed.slice(0,MAX_SHORTLIST_ENTRIES).map(normalize).filter((value):value is ShortlistRecord=>Boolean(value));}catch{return[];}}
function writeShortlist(records:ShortlistRecord[]){localStorage.setItem(SHORTLIST_KEY,JSON.stringify(records.slice(0,MAX_SHORTLIST_ENTRIES)));}
export function toggleShortlist(raw:any){const record=normalize(raw);if(!record)throw new Error('Invalid shortlist record.');const records=loadShortlist();const index=records.findIndex(item=>item.domain===record.domain);if(index>=0)records.splice(index,1);else{if(records.length>=MAX_SHORTLIST_ENTRIES)throw new Error(`Shortlist is limited to ${MAX_SHORTLIST_ENTRIES} domains.`);records.push(record);}writeShortlist(records);return index<0;}
export function clearShortlist(){writeShortlist([]);}
export function importShortlist(value:unknown){if(!Array.isArray(value))throw new Error('Expected a JSON array of shortlist entries.');if(value.length>MAX_SHORTLIST_ENTRIES)throw new Error(`Shortlist imports are limited to ${MAX_SHORTLIST_ENTRIES} domains.`);const byDomain=new Map(loadShortlist().map(record=>[record.domain,record]));let added=0,updated=0;for(const raw of value){const record=normalize(raw);if(!record)continue;byDomain.has(record.domain)?updated++:added++;byDomain.set(record.domain,record);}writeShortlist([...byDomain.values()]);return{added,updated};}
export function exportShortlist(){const url=URL.createObjectURL(new Blob([JSON.stringify(loadShortlist(),null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`whoisleuth-shortlist-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);}
